### ISSUE TITLE
Errors during liveness checking do not terminate TLC

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#1]
NodePtrTable does not overflow to secondary storage and thus always eventually goes OOM if the model is large enough. It also throws an OOM, when NodePtrTable's capacity approaches Integer.MAX_VALUE - the JVM's built-in limit for array. Subsequently an ArrayIndexOutOfBound exception gets thrown because NodePtrTable's length increases prior to the OOM and does not readjusted in case of an OOM.

NodePtrTable.grow() line: 132
NodePtrTable.get(long) line: 76 
DiskGraph.getNode(long) line: 39 
LiveCheck$LiveChecker.addNextState(TLCState, long, SetOfStates, BitVector, boolean[]) line: 454 
LiveCheck.addNextState(TLCState, long, SetOfStates) line: 104 
ModelChecker.doNext(TLCState, ObjLongTable, Worker) line: 619 
Worker.run() line: 57

**Comment by lemmy** [comment]
```java
The exception was a java.lang.OutOfMemoryError
: Java heap space
	at tlc2.util.SynchronousDiskIntStack.<init>(SynchronousDiskIntStack.java:61)
	at tlc2.tool.liveness.LiveWorker.getStack(LiveWorker.java:482)
	at tlc2.tool.liveness.LiveWorker.checkSccs(LiveWorker.java:205)
	at tlc2.tool.liveness.LiveWorker.run(LiveWorker.java:1242)
	at tlc2.tool.liveness.LiveCheck.check0(LiveCheck.java:218)
	at tlc2.tool.liveness.LiveCheck.finalCheck(LiveCheck.java:175)
	at tlc2.tool.ModelChecker.modelCheckImpl(ModelChecker.java:259)
	at tlc2.tool.AbstractChecker.modelCheck(AbstractChecker.java:516)
	at tlc2.TLC.process(TLC.java:1071)
	at tlc2.TLC.main(TLC.java:289)
```

**Comment by lemmy** [comment]
Errors during liveness checking do not terminate TLC.

The error/exception - such as an OutOfMemoryError - shows up on the
console, but does not terminate TLC.  A user thus might miss the
error/exception and incorrectly assume that the spec satisfies the
liveness properties.

The effect of this fix can be studied with unit test
CodePlexBug09EWD749FL2Test that terminates with a meaningful "ran
out of memory" message instead of showing TLC regular success
message despite going out of memory (run test with -Xmx56m).
