### ISSUE TITLE
Warning: the definition of 'Permutations' conflicts with its definition at...

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#103]
```tla
---------------------------- MODULE Permutations ----------------------------

Permutations == TRUE

=============================================================================
```

With the spec above and _Permutations_ evaluated as a constant expression, the Toolbox gets into an inconsistent state. The model is in the [modelchecking] state and the Toolbox has to be restarted.

```
!ENTRY org.lamport.tla.toolbox.tool.tlc 4 0 2017-10-25 21:10:40.557
!MESSAGE Fatal error during validation of the model. SANY discovered an error somewhere else than the MC file. This is a bug. The error message was Unknown location

line 16, col 1 to line 17, col 54 of module TLC

Warning: the definition of 'Permutations' conflicts with 
its definition at line 3, col 1 to line 3, col 20 of module Permutations. in the module TLC.tla
!STACK 1
org.eclipse.core.runtime.CoreException: Fatal error during validation of the model. SANY discovered an error somewhere else than the MC file. This is a bug. The error message was Unknown location

line 16, col 1 to line 17, col 54 of module TLC

Warning: the definition of 'Permutations' conflicts with 
its definition at line 3, col 1 to line 3, col 20 of module Permutations. in the module TLC.tla
	at org.lamport.tla.toolbox.tool.tlc.launch.TLCModelLaunchDelegate.finalLaunchCheck(TLCModelLaunchDelegate.java:598)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:868)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.lamport.tla.toolbox.tool.tlc.model.Model.launch(Model.java:1056)
	at org.lamport.tla.toolbox.tool.tlc.ui.editor.ModelEditor$6.run(ModelEditor.java:832)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.lamport.tla.toolbox.tool.tlc.ui.editor.ModelEditor.launchModel(ModelEditor.java:700)
	at org.lamport.tla.toolbox.tool.tlc.ui.editor.ModelEditor.doSave(ModelEditor.java:374)
	at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:154)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2180)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2176)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:259)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:158)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3917)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3931)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:285)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:506)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:557)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:377)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:323)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:85)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1577)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1347)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:768)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3526)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:785)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1976)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6168)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5512)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9251)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1252)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2110)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4105)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.lamport.tla.toolbox.Application.start(Application.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
!SUBENTRY 1 org.lamport.tla.toolbox.tool.tlc 4 0 2017-10-25 21:10:40.558
!MESSAGE Fatal error during validation of the model. SANY discovered an error somewhere else than the MC file. This is a bug. The error message was Unknown location

line 16, col 1 to line 17, col 54 of module TLC

Warning: the definition of 'Permutations' conflicts with 
its definition at line 3, col 1 to line 3, col 20 of module Permutations. in the module TLC.tla

**Comment by quaeler** [comment]
While i agree this should not sabotage the toolbox and so that part of this is a bug to fix; the SANY error message seems misguided - this isn't a bug, there is indeed a name collision.

Shouldn't we have all formulas defined in [`TLC.tla`](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/StandardModules/TLC.tla) (and any other modules loaded automatically) be either defined as reserved words if they are allowed to be used publicly, or named somewhat obscurely to avoid naming collisions with user defined functions?

**Comment by lemmy** [comment]
Changing the Toolbox to not extend TLC causes it to
marker a symmetric set of model values as broken. This is because it requires the "Permutations(S)" operator from the TLC standard module.
A fix is to insert a local definition of "Permutations(S)" into the MC.tla file generated by the Toolbox similar to what is done in commit 640df81 and 5249fa5.
