### ISSUE TITLE
Flaky unit test: `tlc2.tool.InliningTest`

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#1040]
Here's a test which [failed one CI run](https://github.com/tlaplus/tlaplus/actions/runs/11292507156) then [passed the next](https://github.com/tlaplus/tlaplus/actions/runs/11292693769), with the following error:
```
junit.framework.AssertionFailedError
at tlc2.tool.InliningTest.testSpec(InliningTest.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at util.IsolatedTestCaseRunner.run(IsolatedTestCaseRunner.java:71) 
```
Pointing to this assertion failing:
https://github.com/tlaplus/tlaplus/blob/9fc01661b60af2db3077ed5060fa514c9c9d40cf/tlatools/org.lamport.tlatools/test/tlc2/tool/InliningTest.java#L102-L103

Do we need to increase the runtime of this test to ensure it succeeds?

**Comment by ahelwer** [comment]
This test has not failed in a while. Will reopen if it fails again.
