### ISSUE TITLE
Transpilation PlusCal to TLA+ occasionally throws exception "deleteOutOfSyncFiles"

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#148]
![screenshot from 2018-02-26 21-28-03](https://user-images.githubusercontent.com/88777/36693573-94dc23a6-1b33-11e8-8efb-8a9a33914463.png)

```
!ENTRY org.eclipse.core.jobs 4 2 2018-02-26 21:29:17.594
!MESSAGE An internal error occurred during: "deleteOutOfSyncFiles".
!STACK 0
java.lang.IllegalArgumentException: Attempted to beginRule: R/, does not match outer scope rule: P/BlockingQueuePcal01
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:349)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:85)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:308)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:121)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
	at org.eclipse.core.internal.resources.Workspace.delete(Workspace.java:1359)
	at org.eclipse.core.internal.resources.Workspace.delete(Workspace.java:1342)
	at org.lamport.tla.toolbox.job.DeleteOutOfSyncJob.runInWorkspace(DeleteOutOfSyncJob.java:58)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by lemmy** [comment]
The cause for the exception has likely been taken care of by commit 9bd518ca27029e89ef714cd9ac08f65ab40c01a2. However, it if resurfaces the root cause is in org.lamport.tla.toolbox.ui.provider.SpecContentProvider which deletes stale file on refresh. This is definitely NOT the place to update the model!
