### ISSUE TITLE
TLA+ fails to start after updating

### ISSUE THREAD

**Issue by talex5** [tlaplus/tlaplus#180]
I just used TLA+'s Check For Updates feature. It downloaded something and prompted me to restart. Restarting failed with "An error has occurred" and told me to view the log.

This still happens after I removed the `.tlaplus` directory. The newly created directory contains:

```
$ tree -a
.
└── .metadata
    ├── .lock
    ├── .log
    └── .plugins
        └── org.lamport.tla.toolbox.product.standalone

3 directories, 2 files
```

The log contains:

```
$ cat .metadata/.log 
!SESSION 2018-08-07 10:02:25.465 -----------------------------------------------
eclipse.buildId=1.5.7
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -keyring /Users/tal/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/tal/.eclipse_keyring

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2018-08-07 10:02:26.524
!MESSAGE TLA+ Toolbox started without arguments.

!ENTRY org.eclipse.osgi 4 0 2018-08-07 10:02:26.803
!MESSAGE Application error
!STACK 1
The Toolbox failed to launch because of an unexpected error. Please try to launch the Toolbox with the "-clean" parameter.
If "-clean" does not fix the problem, please open a bug and attach the .log file.

org.lamport.tla.toolbox.Application$2: org.eclipse.e4.core.di.InjectionException: Could not find satisfiable constructor in org.eclipse.e4.ui.internal.workbench.WorkbenchLogger
	at org.lamport.tla.toolbox.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: org.eclipse.e4.core.di.InjectionException: Could not find satisfiable constructor in org.eclipse.e4.ui.internal.workbench.WorkbenchLogger
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:510)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.lamport.tla.toolbox.Application.start(Application.java:141)
	... 12 more
!SESSION 2018-08-07 10:06:01.637 -----------------------------------------------
eclipse.buildId=1.5.7
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -keyring /Users/tal/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/tal/.eclipse_keyring

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2018-08-07 10:06:02.699
!MESSAGE TLA+ Toolbox started without arguments.

!ENTRY org.eclipse.osgi 4 0 2018-08-07 10:06:02.982
!MESSAGE Application error
!STACK 1
The Toolbox failed to launch because of an unexpected error. Please try to launch the Toolbox with the "-clean" parameter.
If "-clean" does not fix the problem, please open a bug and attach the .log file.

org.lamport.tla.toolbox.Application$2: org.eclipse.e4.core.di.InjectionException: Could not find satisfiable constructor in org.eclipse.e4.ui.internal.workbench.WorkbenchLogger
	at org.lamport.tla.toolbox.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: org.eclipse.e4.core.di.InjectionException: Could not find satisfiable constructor in org.eclipse.e4.ui.internal.workbench.WorkbenchLogger
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:510)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.lamport.tla.toolbox.Application.start(Application.java:141)
	... 12 more
```

I don't know how to pass `-clean` to it.

**Comment by talex5** [comment]
However, removing `/Applications/TLA+ Toolbox.app` and reinstalling manually did fix it.

**Comment by lemmy** [comment]
@talex5 Do you still have the broken installation? If yes, please try launching the Toolbox with the "-clean" parameter by editing the toolbox.ini file. "-clean" has to appear directly before "-vmargs". Thx

**Comment by talex5** [comment]
Just tried it on the old version.

It failed to start when I ran it initially.
Then I added `-clean` and it worked.
Then I removed `-clean`, and it still works.

Where is it storing the extra state?

**Comment by lemmy** [comment]
.tlaplus/ in your user's home directory.

I've considered adding "-clean" to toolbox.ini as a default in the past. I assume it delays Toolbox startup by 23,42ms.

**Comment by talex5** [comment]
Hmm. I thought that it still failed to start after I moved the old `.tlaplus` directory out of the way this morning.

**Comment by lemmy** [comment]
There is additional state in the `configuration` directory under `/Applications/TLA+ Toolbox.app`.

**Comment by lemmy** [comment]
I wonder if the internal update mechanism should be retired or not. It adds little value but creates non-negligible work.

**Comment by peterwvj** [comment]
I ran into this issue too. Passing the`-clean` option fixed it. You should strongly consider making this the default  behavior.

**Comment by lemmy** [comment]
842f0be7c85a505547d135ae1f83d8ce956483c9
