### ISSUE TITLE
IllegalArgumentException on symmetry set with one element

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#218]
```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at util.Set.<init>(Set.java:86)
	at util.Set.<init>(Set.java:100)
	at tlc2.value.MVPerm.permutationSubgroup(MVPerm.java:95)
	at tlc2.tool.Tool.getSymmetryPerms(Tool.java:3100)
	at tlc2.tool.TLCStateMutSource.init(TLCStateMutSource.java:67)
	at tlc2.tool.Tool.init(Tool.java:114)
	at tlc2.tool.AbstractChecker.<init>(AbstractChecker.java:127)
	at tlc2.tool.ModelChecker.<init>(ModelChecker.java:97)
	at tlc2.tool.ModelChecker.<init>(ModelChecker.java:77)
	at tlc2.TLC.process(TLC.java:928)
	at tlc2.TLC.main(TLC.java:247)
```

Fix: Show a meaningful error message.

**Comment by lemmy** [comment]
Show a meaningful error message.

**Comment by quaeler** [comment]
Closed with 0b9f474

**Comment by quaeler** [comment]
Reopening while improvements afoot.

**Comment by quaeler** [comment]
Improved messaging and handling of unions provided with 5544517
