### ISSUE TITLE
Class Not Found Exception: javax.activation.DataSource

### ISSUE THREAD

**Issue by agentultra** [tlaplus/tlaplus#231]
Trying to run tlc on the command line gives:

```
TLC2 Version 2.13 of 18 July 2018
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at tlc2.TLC.main(TLC.java:210)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

Tried using both `java tlc2.TLC MyModule.tla` and a compiled binary of tlc as well with no dice. I'm not terribly familiar with the Java Ecosystem either but I haven't been able to downgrade my JRE/JDK either in case it's some missing/deprecated libraries or something.

MacOS 10.12.6
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by lemmy** [comment]
@agentultra Please try with a [recent nightly build](http://dl.tlapl.us/tlatoolbox/ci/products/) which fixes a possibly [related issue](https://github.com/tlaplus/tlaplus/commit/96b4ea1c0bf60d930c856204da42f2b21f6858c3).

**Comment by lemmy** [comment]
Closing per previous comment.
