### ISSUE TITLE
Thousands separator for progress stats

### ISSUE THREAD

**Issue by philipmw** [tlaplus/tlaplus#236]
Right now, progress stat line (`EC.TLC_PROGRESS_STATS`) looks like this:

> Progress(32) at 2019-02-19 20:28:11: 516608828 states generated (432,270 s/min), 19621926 distinct states found (14,277 ds/min), 1433419 states left on queue.

There are some huge numbers that need thousands separators for readability. I propose it to look like this:

> Progress(32) at 2019-02-19 20:28:11: 516,608,828 states generated (432,270 s/min), 19,621,926 distinct states found (14,277 ds/min), 1,433,419 states left on queue.

I'm happy to implement this change, but I wanted to first check with you whether you see any issues with this enhancement.

**Comment by lemmy** [comment]
@philipmw A patch will be accepted if
a) it uses the system's locale to select the thousands delimiter
b) the Toolbox's parser - which reads TLC's output - does not break or gets changed correspondingly

To work around b) it might be acceptable to only print a thousands delimiter in TLC's non-Tool mode

**Comment by lemmy** [comment]
```
!ENTRY org.lamport.tla.toolbox.tool.tlc.ui 4 0 2019-03-20 16:11:39.356
!MESSAGE Error reading progress information
!STACK 0
java.lang.NumberFormatException: For input string: "9,341"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.lamport.tla.toolbox.tool.tlc.output.data.StateSpaceInformationItem.parseOld(StateSpaceInformationItem.java:289)
	at org.lamport.tla.toolbox.tool.tlc.output.data.StateSpaceInformationItem.parse(StateSpaceInformationItem.java:169)
	at org.lamport.tla.toolbox.tool.tlc.output.data.TLCModelLaunchDataProvider.onOutput(TLCModelLaunchDataProvider.java:444)
	at org.lamport.tla.toolbox.tool.tlc.output.source.CachingTLCOutputSource.onOutput(CachingTLCOutputSource.java:90)
	at org.lamport.tla.toolbox.tool.tlc.output.source.CachingTLCOutputSource.onOutput(CachingTLCOutputSource.java:58)
	at org.lamport.tla.toolbox.tool.tlc.output.source.TagBasedTLCOutputIncrementalParser$TLCOutputPartitionChangeListener.documentPartitioningChanged(TagBasedTLCOutputIncrementalParser.java:278)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentPartitioningChanged(AbstractDocument.java:592)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:735)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:716)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:700)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:774)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1105)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1123)
	at org.lamport.tla.toolbox.tool.tlc.output.source.TagBasedTLCOutputIncrementalParser.addIncrement(TagBasedTLCOutputIncrementalParser.java:398)
	at org.lamport.tla.toolbox.tool.tlc.output.ParsingTLCOutputSink.addIncrement(ParsingTLCOutputSink.java:48)
	at org.lamport.tla.toolbox.tool.tlc.output.ParsingTLCOutputSink.appendText(ParsingTLCOutputSink.java:40)
	at org.lamport.tla.toolbox.tool.tlc.output.internal.BroadcastStreamListener.streamAppended(BroadcastStreamListener.java:44)
	at org.eclipse.debug.internal.core.OutputStreamMonitor$ContentNotifier.run(OutputStreamMonitor.java:265)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.OutputStreamMonitor$ContentNotifier.notifyAppend(OutputStreamMonitor.java:275)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.fireStreamAppended(OutputStreamMonitor.java:121)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.read(OutputStreamMonitor.java:162)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.lambda$0(OutputStreamMonitor.java:212)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by philipmw** [comment]
Oh, no! Do you know how to reproduce this?

**Comment by lemmy** [comment]
Seems to be related to checking liveness.

It also just occurred to me that this change makes MC.out files locale and thus platform dependent.  I lean towards reverting.

**Comment by philipmw** [comment]
I'll support you if you want to revert it.

However, the status quo (before this PR) is that some values had thousands separators already, while others didn't. (And the ones that didn't were difficult to read because the numbers could be huge.) My PR aimed to make all numbers consistently easy to read. Any locale/platform-dependence already existed.

I still think there's virtue in having consistency, so I'd like to reproduce this issue and fix it.

**Comment by lemmy** [comment]
The fix for the actual issue is to also use NumberFormat in org.lamport.tla.toolbox.tool.tlc.output.data.StateSpaceInformationItem.parseOld(String).  

The methods below trigger parseOld:
tlc2.tool.distributed.TLCServer.modelCheck()
tlc2.tool.distributed.TLCServer.printSummary(int, long, long, long, boolean)
tlc2.tool.ModelChecker.modelCheck()


As to MC.out files being locale dependent, TLC could simply use "." regardless of locale.

**Comment by lemmy** [comment]
I also wonder if there is merit in printing thousand delimiters in TLC's _tool_ output.  In this mode, it should be the Toolbox's responsibility to print delimiters.  In non-tool mode, TLC could then continue to respect the user's locale.
