### ISSUE TITLE
TLA+ Syntax Parser throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#298]
![Screenshot from 2019-04-29 20-57-55](https://user-images.githubusercontent.com/88777/56940168-812db700-6ac1-11e9-887b-a8587c4a710a.png)

```java
!ENTRY org.lamport.tla.toolbox.tool.tlc 1 0 2019-04-29 20:56:14.951
!MESSAGE TLC COMMAND-LINE (CWD: /home/markus/src/TLA/_specs/models/tlcbugs/Github297/Github297.toolbox/Model_1): /opt/TLA+Toolbox/plugins/org.lamport.openjdk.linux.x86_64_11.0.3.1/jre/bin/java -XX:MaxDirectMemorySize=3974m -Xmx1989m -Dtlc2.tool.fp.FPSet.impl=tlc2.tool.fp.OffHeapDiskFPSet -XX:+UseParallelGC -DTLA-Library=/usr/local/lib/tlaps/ -Dfile.encoding=UTF-8 -classpath /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201904262021:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201904262021/lib/*:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201904262021/lib/javax.mail/*:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201904262021/class tlc2.TLC -checkpoint 15 -fp 58 -config MC.cfg -coverage 3 -workers 2 -tool -metadir /home/markus/src/TLA/_specs/models/tlcbugs/Github297/Github297.toolbox/Model_1 MC

!ENTRY org.eclipse.core.resources 4 2 2019-04-29 20:56:17.451
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.base/java.util.LinkedList$ListItr.next(Unknown Source)
	at org.lamport.tla.toolbox.spec.parser.ParseResultBroadcaster.broadcastParseResult(ParseResultBroadcaster.java:115)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:368)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:83)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:56)
	at org.lamport.tla.toolbox.spec.parser.SpecificationParserLauncher.parseSpecification(SpecificationParserLauncher.java:38)
	at org.lamport.tla.toolbox.spec.nature.ParserHelper$2.run(ParserHelper.java:68)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2314)
	at org.lamport.tla.toolbox.spec.nature.ParserHelper.rebuildSpec(ParserHelper.java:73)
	at org.lamport.tla.toolbox.spec.nature.TLAParsingBuilder.build(TLAParsingBuilder.java:95)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

Caused by:

1. Model Editor with a TLACoverageEditor is open (the TLACoverageEditor has a org.lamport.tla.toolbox.spec.parser.IParseResultListener registered with org.lamport.tla.toolbox.spec.parser.ParseResultBroadcaster)
2. User hits "Run TLC on the model" which causes a spec parse which in turn triggers the ParseResultBroadcaster
3. The Model Editor dispose methods de-register the org.lamport.tla.toolbox.editor.basic.proof.TLAProofFoldingStructureProvider when closing the TLACoverageEditor instance)

A CopyOnWriteArrayList appears to be the easiest fix.

**Comment by lemmy** [comment]
@quaeler Can you please review my analysis above and indicate agreement?

**Comment by quaeler** [comment]
Yep - looks like sound reasoning and agree on the easiest fix.
