### ISSUE TITLE
Toolbox shows ghost model after deletion

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#30]
A ghost remains after Model_4 is deleted (see image below). As a workaround, closing and re-opening the specification removes the ghost model.

--------------------------------------------------------------------------------

![image001](https://cloud.githubusercontent.com/assets/88777/21093362/a464fe12-c051-11e6-9661-cb6c60fc4b7a.png)

The Eclipse console shows:

    org.eclipse.debug.core.DebugException: Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
       at org.eclipse.debug.internal.core.LaunchManager.createDebugException(LaunchManager.java:930)
       at org.eclipse.debug.internal.core.LaunchManager.getInfo(LaunchManager.java:1400)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getInfo(LaunchConfiguration.java:470)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getAttribute(LaunchConfiguration.java:416)
       at org.lamport.tla.toolbox.tool.tlc.model.Model.getName(Model.java:245)
       at org.lamport.tla.toolbox.tool.tlc.ui.modelexplorer.ModelLabelProvider.getText(ModelLabelProvider.java:57)
       at org.eclipse.ui.internal.navigator.extensions.SafeDelegateCommonLabelProvider.getText(SafeDelegateCommonLabelProvider.java:112)
       at org.eclipse.ui.internal.navigator.extensions.SafeDelegateCommonLabelProvider.getStyledText(SafeDelegateCommonLabelProvider.java:120)
       at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.findStyledText(NavigatorContentServiceLabelProvider.java:167)
       at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getStyledText(NavigatorContentServiceLabelProvider.java:153)
       at org.eclipse.ui.internal.navigator.NavigatorDecoratingLabelProvider$StyledLabelProviderAdapter.getStyledText(NavigatorDecoratingLabelProvider.java:63)
       at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getStyledText(DelegatingStyledCellLabelProvider.java:206)
       at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getStyledText(DecoratingStyledCellLabelProvider.java:199)
       at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:106)
       at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:136)
       at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:154)
       at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:949)
       at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:114)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
       at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
       at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1029)
       at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:473)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
       at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
       at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2176)
       at org.eclipse.jface.viewers.StructuredViewer.internalUpdate(StructuredViewer.java:2159)
       at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2097)
       at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:541)
       at org.eclipse.ui.navigator.CommonViewer.update(CommonViewer.java:510)
       at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2041)
       at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1208)
       at org.eclipse.ui.navigator.CommonViewer.handleLabelProviderChanged(CommonViewer.java:236)
       at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:99)
       at org.eclipse.jface.viewers.BaseLabelProvider$1.run(BaseLabelProvider.java:72)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
       at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
       at org.eclipse.jface.viewers.BaseLabelProvider.fireLabelProviderChanged(BaseLabelProvider.java:69)
       at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider$1.labelProviderChanged(DecoratingStyledCellLabelProvider.java:78)
       at org.eclipse.ui.internal.decorators.DecoratorManager$1.run(DecoratorManager.java:446)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.decorators.DecoratorManager.fireListener(DecoratorManager.java:443)
       at org.eclipse.ui.internal.decorators.DecorationScheduler$3.runInUIThread(DecorationScheduler.java:536)
       at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
       at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
       at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
       at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
       at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
       at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
       at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
       at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
       at org.lamport.tla.toolbox.Application.start(Application.java:77)
       at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
       at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
       at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
       at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
       !SUBENTRY 1 org.eclipse.debug.core 4 5012 2016-12-11 12:37:24.318
       !MESSAGE Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.

 
Clicking on the ghost icon (with blank name) produced the following exception:
      
``` 
!ENTRY org.lamport.tla.toolbox.tool.tlc 4 0 2016-12-11 12:41:51.857
!MESSAGE Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
!STACK 1
org.eclipse.debug.core.DebugException: Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
       at org.eclipse.debug.internal.core.LaunchManager.createDebugException(LaunchManager.java:930)
       at org.eclipse.debug.internal.core.LaunchManager.getInfo(LaunchManager.java:1400)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getInfo(LaunchConfiguration.java:470)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getAttribute(LaunchConfiguration.java:416)
       at org.lamport.tla.toolbox.tool.tlc.model.Model.getComments(Model.java:254)
       at org.lamport.tla.toolbox.tool.tlc.ui.modelexplorer.ModelLabelProvider.getDescription(ModelLabelProvider.java:77)
       at org.eclipse.ui.internal.navigator.extensions.SafeDelegateCommonLabelProvider.getDescription(SafeDelegateCommonLabelProvider.java:79)
       at org.eclipse.ui.internal.navigator.NavigatorContentServiceDescriptionProvider.getDescription(NavigatorContentServiceDescriptionProvider.java:66)
       at org.eclipse.ui.navigator.CommonNavigatorManager.updateStatusBar(CommonNavigatorManager.java:321)
       at org.eclipse.ui.navigator.CommonNavigatorManager$1.selectionChanged(CommonNavigatorManager.java:75)
       at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:877)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
       at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
       at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:874)
       at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1243)
       at org.eclipse.ui.navigator.CommonViewer.handlePostSelect(CommonViewer.java:455)
       at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1269)
       at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
       at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
       at org.eclipse.jface.util.OpenStrategy$1$2.run(OpenStrategy.java:440)
       at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
       at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
       at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
       at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
       at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
       at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
       at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
       at org.lamport.tla.toolbox.Application.start(Application.java:77)
       at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
       at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
       at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
       at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
!SUBENTRY 1 org.eclipse.debug.core 4 5012 2016-12-11 12:41:51.858
!MESSAGE Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.

 
!ENTRY org.lamport.tla.toolbox.tool.tlc 4 0 2016-12-11 12:41:51.870
!MESSAGE Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
!STACK 1
org.eclipse.debug.core.DebugException: Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
       at org.eclipse.debug.internal.core.LaunchManager.createDebugException(LaunchManager.java:930)
       at org.eclipse.debug.internal.core.LaunchManager.getInfo(LaunchManager.java:1400)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getInfo(LaunchConfiguration.java:470)
       at org.eclipse.debug.internal.core.LaunchConfiguration.getAttribute(LaunchConfiguration.java:416)
       at org.lamport.tla.toolbox.tool.tlc.model.Model.getName(Model.java:245)
       at org.lamport.tla.toolbox.tool.tlc.ui.modelexplorer.ModelLabelProvider.getText(ModelLabelProvider.java:57)
       at org.lamport.tla.toolbox.tool.tlc.ui.modelexplorer.ModelLabelProvider.getDescription(ModelLabelProvider.java:79)
       at org.eclipse.ui.internal.navigator.extensions.SafeDelegateCommonLabelProvider.getDescription(SafeDelegateCommonLabelProvider.java:79)
       at org.eclipse.ui.internal.navigator.NavigatorContentServiceDescriptionProvider.getDescription(NavigatorContentServiceDescriptionProvider.java:66)
       at org.eclipse.ui.navigator.CommonNavigatorManager.updateStatusBar(CommonNavigatorManager.java:321)
       at org.eclipse.ui.navigator.CommonNavigatorManager$1.selectionChanged(CommonNavigatorManager.java:75)
       at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:877)
       at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
       at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
       at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
       at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:874)
       at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1243)
       at org.eclipse.ui.navigator.CommonViewer.handlePostSelect(CommonViewer.java:455)
       at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1269)
       at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
       at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
       at org.eclipse.jface.util.OpenStrategy$1$2.run(OpenStrategy.java:440)
       at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
       at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
       at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
       at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
       at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
       at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
       at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
       at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
       at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
       at org.lamport.tla.toolbox.Application.start(Application.java:77)
       at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
       at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
       at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
       at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
       at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
!SUBENTRY 1 org.eclipse.debug.core 4 5012 2016-12-11 12:41:51.872
!MESSAGE Launch configuration DieHard___Model_4 at file:/C:/lamport/talks/microsoft16/DieHard.toolbox/DieHard___Model_4.launch does not exist.
```

**Comment by quaeler** [comment]
I cannot replicate this in the 1.5.7 release - can you @lemmy ?

**Comment by lemmy** [comment]
Closing given the lack of instructions to reproduce.  Please reopen with reproducible instructions.
