### ISSUE TITLE
Tautological liveness property causes IllegalArgumentException

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#302]
```tla
VARIABLES x

Init == x = 0
Next == x' = 1

Prop == <>[](TRUE) => TRUE
```

```java
The exception was a java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:269)
	at java.base/java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:254)
	at tlc2.tool.liveness.LiveCheck.check0(LiveCheck.java:219)
	at tlc2.tool.liveness.LiveCheck.finalCheck(LiveCheck.java:184)
	at tlc2.tool.ModelChecker.modelCheck(ModelChecker.java:242)
	at tlc2.TLC.process(TLC.java:939)
	at tlc2.TLC.main(TLC.java:252)

```

**Comment by lemmy** [comment]
9b64867eba5b6301b307ea21b0b878eb4e3e8632
