### ISSUE TITLE
Eclipse IDE intermittently fails to resolve dependencies properly when developing TLA+ Toolbox

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#311]
When developing the TLA+ Toolbox in Eclipse (having followed [this](https://github.com/tlaplus/tlaplus/tree/ee2f998471504a0ded1372cf32b412ffa002059a/general/ide) setup guide), I sometimes end up in a case where Eclipse is suddenly unable to find the proper dependencies for the project e.g.

<img width="1440" alt="Screen Shot 2019-05-20 at 8 03 41 PM" src="https://user-images.githubusercontent.com/6131840/58059342-68517800-7b3a-11e9-8685-520689ebad96.png">

It may be related to this error message that is displayed when trying to execute the Eclipse startup tasks:

```
Executing startup tasks
Java(TM) SE Runtime Environment 11.0.2+9-LTS
Product org.eclipse.products.org.eclipse.platform.ide.latest.released
Workspace /Users/williamschultz/Documents/TLAPlusDevelopment/tlaplus-master-2018-12/ws
Project com.github.tlaplus.master
Bundle org.eclipse.oomph.setup 1.13.0.v20190511-0841, build=3979, branch=d54086116a9c5298f6eb3f4fdb8392397d8bed9f
Bundle org.eclipse.oomph.setup.core 1.13.0.v20190511-0841, build=3979, branch=d54086116a9c5298f6eb3f4fdb8392397d8bed9f
Bundle org.eclipse.oomph.setup.git 1.13.0.v20190511-0841, build=3979, branch=d54086116a9c5298f6eb3f4fdb8392397d8bed9f
Bundle org.eclipse.oomph.setup.jdt 1.12.0.v20190511-0841, build=3979, branch=d54086116a9c5298f6eb3f4fdb8392397d8bed9f
Bundle org.eclipse.oomph.setup.p2 1.10.0.v20180706-1242, build=3827, branch=4e5724653144559ceea47aca17cc41b2abeb6745
Bundle org.eclipse.oomph.setup.pde 1.10.0.v20180706-1242, build=3827, branch=4e5724653144559ceea47aca17cc41b2abeb6745
Bundle org.eclipse.oomph.setup.projects 1.10.0.v20180706-1242, build=3827, branch=4e5724653144559ceea47aca17cc41b2abeb6745
Bundle org.eclipse.oomph.setup.workingsets 1.10.0.v20180706-1242, build=3827, branch=4e5724653144559ceea47aca17cc41b2abeb6745
Performing Target Platform TLA+ Toolbox
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.setup.pde.impl.TargetPlatformTaskImpl.perform(TargetPlatformTaskImpl.java:293)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3335)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3278)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4514)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4508)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4506)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3269)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3244)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3144)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.contribution.weaving.feature.group 2.2.4.201805281636
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.ajdt.feature.group 2.2.4.201805281636
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.log4j 1.2.15.v201012070815
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest 1.1.0.v20090501071000
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit com.jcraft.jsch 0.1.54.v20170116-1932
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.commons.io 2.2.0.v201405211200
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.commons.collections 3.2.2.v201511171945
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit javax.activation 1.1.0.v201211130549
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit javax.mail 1.4.0.v201005080615
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.easymock 2.4.0.v20090202-0900
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.swtbot.ide.feature.group 2.7.0.201806111355
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.swtbot.eclipse.test.junit.feature.group 2.7.0.201806111355
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.swtbot.feature.group 2.7.0.201806111355
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.swtbot.eclipse.feature.group 2.7.0.201806111355
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.jclouds.feature.feature.group 0.0.0
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.help.feature.group 2.2.300.v20180906-0745
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.equinox.core.sdk.feature.group 3.15.0.v20180827-1536
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.platform.feature.group 4.9.0.v20180906-1121
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.rcp.configuration.feature.group 1.1.200.v20180906-0745
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.emf.ecore.feature.group 2.15.0.v20180722-1159
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.equinox.executable 3.8.100.v20180827-1352
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.ecf.core.feature.feature.group 1.5.1.v20180810-0833
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.e4.rcp.feature.group 1.6.200.v20180906-1121
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.emf.common.feature.group 2.15.0.v20180723-1316
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.equinox.sdk.feature.group 3.15.0.v20180904-1442
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.core.runtime.feature.feature.group 1.2.200.v20180903-1343
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.jdt.feature.group 3.15.0.v20180906-0745
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.pde.source.feature.group 3.13.200.v20180906-0745
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit de.vonloesch.pdf4eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.lamport.openjdk.feature.feature.group 0.0.0
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit com.abstratt.eclipsegraphviz.feature.feature.group 2.5.201812
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.recommenders.news.rcp.feature.feature.group 2.5.4.v20180909-1132
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.mylyn.commons.feature.group 3.24.2.v20180904-2231
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.mylyn.commons.notifications.feature.group 1.16.0.v20180904-2231
  ERROR: org.eclipse.pde.core code=0 Problems loading repositories
    ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.e4.tools.spies.feature.feature.group 0.0.0
```
This is my Eclipse version information:
```
Eclipse Platform

Version: 2019-03 (4.11)
Build id: I20190307-0500
```
and I am developing on Mac OSX 10.13.6. I am not sure but it seems this issue may arise when I manually build the Toolbox from the command line i.e. running something like `mvn clean verify`. I'm posting this as a Github issue so that if others face this in the future they can use this thread as a reference.

**Comment by lemmy** [comment]
@quaeler Do you observe similar behavior (I don't on Linux).

**Comment by quaeler** [comment]
I don't on the same version of macOS - but i do avoid having Eclipse running when i do maven builds as i've seen Eclipse have workspace problems if it's running concurrently.

I also avoid having Oomph run its setup tasks at startup as it has historically produced headaches.

**Comment by lemmy** [comment]
I cannot confirm either of those two behaviors.

**Comment by lemmy** [comment]
Please re-open if this is still an issue
