### ISSUE TITLE
Enablement of menu items

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#335]
1. Snapshot Cannot rename but option is available
![thumbnail_image001](https://user-images.githubusercontent.com/88777/61092516-6ea5f700-a3fb-11e9-95ce-2902991f6ea6.png)
2. Open with in-place editor: Unable to restore in-place editor. In-place support is missing.
```java
org.eclipse.ui.PartInitException: Unable to restore in-place editor. In-place support is missing.
                at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:328)
                at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:305)
                at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPart(CompatibilityEditor.java:66)
                at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:343)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
                at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1001)
                at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:966)
                at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
                at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)
                at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)
                at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:193)
                at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:108)
                at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:77)
                at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:59)
                at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1015)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:675)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:781)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:752)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:746)
                at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:730)
                at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:107)
                at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
                at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
                at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:147)
                at org.eclipse.swt.widgets.Display.syncExec(Display.java:4594)
                at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:215)
                at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
                at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:204)
                at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:199)
                at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
                at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
                at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
                at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:138)
                at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:81)
                at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:42)
                at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
                at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
                at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
                at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:177)
                at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:637)
                at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:601)
                at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:791)
                at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1238)
                at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3298)
                at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3197)
                at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
                at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3194)
                at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3158)
                at org.eclipse.ui.actions.OpenWithMenu.openEditor(OpenWithMenu.java:326)
                at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor$17.openEditor(AbstractDecoratedTextEditor.java:2001)
                at org.eclipse.ui.actions.OpenWithMenu.lambda$0(OpenWithMenu.java:183)
                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
                at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
                at org.lamport.tla.toolbox.Application.start(Application.java:141)
                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
                at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
                at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by quaeler** [comment]
Addressed with 2a975da and f95d243
