### ISSUE TITLE
cannot start TLA+ Toolbox application from Eclipse Oomph 2018.12

### ISSUE THREAD

**Issue by keepsimple1** [tlaplus/tlaplus#348]
I installed Eclipse Oomph 2018.12 with Java 11 (AdoptOpenJDK11), but when I try to run the TLA+ Toolbox application, it failed to load SWT library due to missing code signature on the lib file (`libswt-cocoa-4919.jnilib`),

here is the detailed error message.  Is this a known issue?

```
!ENTRY org.eclipse.osgi 4 0 2019-08-08 11:10:04.463
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/Users/hanxu/work/tlaplus-master/ws/.metadata/.plugins/org.eclipse.pde.core/org.lamport.tla.toolbox.product.product.product/org.eclipse.osgi/211/0/.cp/libswt-cocoa-4919.jnilib: dlopen(/Users/hanxu/work/tlaplus-master/ws/.metadata/.plugins/org.eclipse.pde.core/org.lamport.tla.toolbox.product.product.product/org.eclipse.osgi/211/0/.cp/libswt-cocoa-4919.jnilib, 1): no suitable image found.  Did find:
	/Users/hanxu/work/tlaplus-master/ws/.metadata/.plugins/org.eclipse.pde.core/org.lamport.tla.toolbox.product.product.product/org.eclipse.osgi/211/0/.cp/libswt-cocoa-4919.jnilib: code signature in (/Users/hanxu/work/tlaplus-master/ws/.metadata/.plugins/org.eclipse.pde.core/org.lamport.tla.toolbox.product.product.product/org.eclipse.osgi/211/0/.cp/libswt-cocoa-4919.jnilib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	no swt-cocoa in java.library.path: [/Users/hanxu/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	/Users/hanxu/.swt/lib/macosx/x86_64/libswt-cocoa-4919.jnilib: dlopen(/Users/hanxu/.swt/lib/macosx/x86_64/libswt-cocoa-4919.jnilib, 1): no suitable image found.  Did find:
	/Users/hanxu/.swt/lib/macosx/x86_64/libswt-cocoa-4919.jnilib: code signature in (/Users/hanxu/.swt/lib/macosx/x86_64/libswt-cocoa-4919.jnilib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	Can't load library: /Users/hanxu/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:330)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:242)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:106)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:733)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:163)
	at org.lamport.tla.toolbox.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
An error has occurred. See the log file
/Users/hanxu/work/tlaplus-master/runtime-org.lamport.tla.toolbox.product.product.product/.metadata/.log.
```

**Comment by lemmy** [comment]
Is the MacOS specific SWT fragment included in the launch config?

**Comment by keepsimple1** [comment]
I am pretty new to Eclipse-based applications. @lemmy did you mean the `Plug-ins` in the `Run Configurations...` ?  see attached screenshot.   
<img width="799" alt="Screen Shot 2019-08-10 at 1 59 17 PM" src="https://user-images.githubusercontent.com/7699244/62826815-792ceb00-bb77-11e9-8ddd-0449b90b080b.png">

The line item highlighted seems to have `Auto-start` set to `false`.  Is that a problem?  Or did you refer something different?

**Comment by lemmy** [comment]
@keepsimple1 The launch config looks good to me. @quaeler any idea what is going on here?

**Comment by quaeler** [comment]
This doesn't ring a bell - @keepsimple1 what macOS version is this?

**Comment by keepsimple1** [comment]
@quaeler macOS is Mojave 10.14.5

**Comment by lemmy** [comment]
Any progress on this?

**Comment by quaeler** [comment]
None on my side - i'm not on Mojave.

**Comment by lemmy** [comment]
Looking at the error again, might this be related to too strict security settings?

```
(/.../libswt-cocoa-4919.jnilib) not valid for use in process using Library Validation:
mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

Compare https://github.com/ycm-core/YouCompleteMe/issues/3158

**Comment by quaeler** [comment]
Were this the genesis though, it seems like no one launching an SWT-dependent RCP from Eclipse under Mojave would be successful.. :- ?

**Comment by keepsimple1** [comment]
Can I ask where I can find the dependency definition of `libswt-cocoa` in this project?  I am not very familiar with Eclipse based projects. I am trying to see if possible update/change to a different version of libswt. Thanks.

**Comment by quaeler** [comment]
It is part of the cocoa-specific SWT bundle which arrives by specifying a dependency on `org.eclipse.swt` in the `META-INF/MANIFEST.MF` [found here.](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.product.standalone/META-INF/MANIFEST.MF#L15)

**Comment by lemmy** [comment]
Before you go down this rabbit hole, I'd try to run a newly generated Eclipse (not Toolbox) launch config.

**Comment by lemmy** [comment]
Please reopen if this is still an issue.
