### ISSUE TITLE
Toolbox does not handle garbaged spec gracefully

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#39]
LL: "I tried opening a spec and it opened with a "Failed to create the part's controls" error, which seemed to be caused by an inability to open the root module.  It was a garbage spec, and I thought I had probably deleted the root module, so I deleted the spec.  I then tried to open a new spec with the same root module.  It created the spec but produced the same error, with the “details” appended below.  I observed that the root file actually did exist.  Also, in the file explorer, the list of modules includes both the root file (Test.tla) and an EXTENDed library module (TLAPS.tla), indicating that the root module was successfully parsed.  Double-clicking on TLAPS in the spec explorer opened that file, but double-clicking on the root module produced the same error. So I deleted the spec again and then deleted the root file and opened a new spec by the same name. It was aware that the specified root file did not exist, but it still produced the same error. I’ve attached the two files that were in the .toolbox directory. I then deleted the spec, closed the Toolbox, re-opened it, and tried again to create the new spec Test. This time it worked."

`
java.lang.IllegalArgumentException: Argument not valid
      at org.eclipse.swt.SWT.error(SWT.java:4472)
      at org.eclipse.swt.SWT.error(SWT.java:4406)
      at org.eclipse.swt.SWT.error(SWT.java:4377)
      at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:9885)
      at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:9979)
      at org.eclipse.jface.text.TextViewer.applyTextPresentation(TextViewer.java:4884)
      at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4936)
      at org.eclipse.jface.text.presentation.PresentationReconciler.applyTextRegionCollection(PresentationReconciler.java:582)
      at org.eclipse.jface.text.presentation.PresentationReconciler.processDamage(PresentationReconciler.java:571)
      at org.eclipse.jface.text.presentation.PresentationReconciler.access$3(PresentationReconciler.java:567)
      at org.eclipse.jface.text.presentation.PresentationReconciler$InternalListener.inputDocumentChanged(PresentationReconciler.java:119)
      at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2890)
      at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2939)
      at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:643)
      at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:375)
      at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:591)
      at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:4050)
      at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3578)
      at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:54)
      at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:447)
      at org.lamport.tla.toolbox.editor.basic.TLAEditor.createPartControl(TLAEditor.java:302)
      at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:244)
      at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:325)
      at org.lamport.tla.toolbox.editor.basic.TLAEditorAndPDFViewer.addPages(TLAEditorAndPDFViewer.java:79)
      at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:138)
      at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:363)
      at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
      at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
      at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:341)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
      at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
      at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
      at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
      at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
      at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
      at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
      at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
      at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:99)
      at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
      at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
      at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
      at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
      at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
      at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
      at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
      at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
      at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
      at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
      at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
      at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
      at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
      at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
      at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
      at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
      at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
      at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
      at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:572)
      at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:536)
      at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
      at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:396)
      at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1166)
      at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3252)
      at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3167)
      at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3149)
      at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
      at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3144)
      at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3108)
      at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3089)
      at org.lamport.tla.toolbox.util.UIHelper.openEditor(UIHelper.java:352)
      at org.lamport.tla.toolbox.ui.handler.OpenSpecHandler$1$1.runInUIThread(OpenSpecHandler.java:79)
      at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
      at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
      at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
      at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
      at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
      at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
      at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
      at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
      at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
      at org.lamport.tla.toolbox.Application.start(Application.java:77)
      at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
      at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
      at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
      at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
`

**Comment by quaeler** [comment]
2+ years later - do you perchance still have the files he mentioned that we was attaching to his report?

**Comment by lemmy** [comment]
I'm afraid not
