### ISSUE TITLE
NPE in TLAReconcilingStrategy.determineFoldingRegions when spec does not end in empty newline

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#414]
```java
Exception in thread "org.eclipse.jface.text.reconciler.MonoReconciler" java.lang.NullPointerException
	at org.lamport.tla.toolbox.editor.basic.TLAReconcilingStrategy.determineFoldingRegions(TLAReconcilingStrategy.java:297)
	at org.lamport.tla.toolbox.editor.basic.TLAReconcilingStrategy.reconcile(TLAReconcilingStrategy.java:164)
	at org.lamport.tla.toolbox.editor.basic.TLAReconcilingStrategy.initialReconcile(TLAReconcilingStrategy.java:133)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:98)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:177)
```

```tla
--------------- MODULE BinaryTree ---------------
EXTENDS Sequences, Naturals

VARIABLES x

Init == /\ x = ""
       
Next == /\ \E s \in {"a", "b"} : x' = x \o s

==================================================
\* This line is NOT followed by a newline
```

**Comment by quaeler** [comment]
Addressed with 7d274ad
