### ISSUE TITLE
a submodule that extends an empty submodule raises an error

### ISSUE THREAD

**Issue by johnyf** [tlaplus/tlaplus#429]
SANY raises an exception for a submodule that extends an empty submodule.

```tla
-------------------------- MODULE ExtendsEmptySubmodule ------------------------

---- MODULE Empty ----
======================


---- MODULE ExtendsEmpty ----
EXTENDS Empty  (* This statement raises an exception. *)
=============================


================================================================================
```

SANY does not raise an error for a module that extends an empty module.

```tla
---- MODULE EmptyModule ----

============================
```

```tla
---- MODULE ExtendsEmptyModule ----
EXTENDS EmptyModule  (* This statement does not raise an error. *)


===================================
```

**Comment by quaeler** [comment]
To clarify, I don't see SANY emitting a parsing exception, I do see an NPE being raised from `Context#mergeExtendContext(Context)` - full-ish stack trace trace as follows:
```
java.lang.NullPointerException
	at tla2sany.semantic.Context.mergeExtendContext(Context.java:370)
	at tla2sany.semantic.Generator.processExtendsList(Generator.java:2168)
	at tla2sany.semantic.Generator.generateModule(Generator.java:2010)
	at tla2sany.semantic.Generator.generateModule(Generator.java:2053)
	at tla2sany.semantic.Generator.generate(Generator.java:1973)
	at tla2sany.drivers.SANY.frontEndSemanticAnalysis(SANY.java:301)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:162)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:83)
	at org.lamport.tla.toolbox.spec.parser.ModuleParserLauncher.parseModule(ModuleParserLauncher.java:56)
	at org.lamport.tla.toolbox.spec.parser.SpecificationParserLauncher.parseSpecification(SpecificationParserLauncher.java:38)
	at org.lamport.tla.toolbox.spec.nature.ParserHelper$2.run(ParserHelper.java:68)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.lamport.tla.toolbox.spec.nature.ParserHelper.rebuildSpec(ParserHelper.java:73)
	at org.lamport.tla.toolbox.spec.nature.TLAParsingBuilder.build(TLAParsingBuilder.java:95)
   ...
```

**Comment by quaeler** [comment]
This is addressed by 14633c7

**Comment by quaeler** [comment]
Or perhaps the unit test tweak in f48335a will pass on the CI machine.

**Comment by johnyf** [comment]
Thank you for addressing this issue.
