### ISSUE TITLE
Update to JDK 14.0.1

### ISSUE THREAD

**Issue by pron** [tlaplus/tlaplus#442]
[14.0.1 is out](http://jdk.java.net/14/)

**Comment by lemmy** [comment]
Show stopper: https://openjdk.java.net/jeps/367

**Comment by lemmy** [comment]
```java
!ENTRY org.lamport.tla.toolbox.jcloud 4 0 2020-04-24 19:56:57.687
!MESSAGE java.lang.NoClassDefFoundError: java/util/jar/Pack200
!STACK 0
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at org.lamport.tla.toolbox.jcloud.CloudDistributedTLCJob.run(CloudDistributedTLCJob.java:249)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at org.lamport.tla.toolbox.jcloud.PayloadHelper.appendModel2Jar(PayloadHelper.java:148)
	at org.lamport.tla.toolbox.jcloud.CloudDistributedTLCJob.lambda$0(CloudDistributedTLCJob.java:170)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:424)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more
```

**Comment by pron** [comment]
Yeah, it's been terminally deprecated since 11. The [compression stage](https://github.com/tlaplus/tlaplus/blob/ab14a33e39c78e4c88e81b664b9a8c916b943cab/toolbox/org.lamport.tla.toolbox.jclouds/src/org/lamport/tla/toolbox/jcloud/PayloadHelper.java#L148) can be skipped.

**Comment by lemmy** [comment]
The pack200 has been removed from CloudTLC at the cost of >2x amount of data to be transferred.

**Comment by pron** [comment]
You can save *much* more than that by not provisioning the nodes with a full JDK, but with a custom minimal runtime created with `jlink`, that is small, and can compress not only the TLA JARs, but also the runtime itself (probably will need to wait for next release :))

**Comment by lemmy** [comment]
The JDK isn't the issue because that's already part of the base image.  What gets transferred is `tla2tools.jar` + spec files (embedded in tla2tools.jar).  `tla2tools.pack.gz` has less than half the size of `tla2tools.jar`.

**Comment by pron** [comment]
That's true, but the image could be made much smaller, and include and compress even tla2tools.jar. Then you'd send only the spec, perhaps embedded in a small JAR, possibly with overrides. Overall, maybe time and data could be saved.

Anyway, Pack200 is gone never to return... Too much work for too little demand.

**Comment by lemmy** [comment]
Unless I see growth in adoption of CloudTLC, I'm not going to provide custom base images.  The beauty of the current implementation is, that CloudTLC runs completely under the user's subscription without non-standard dependencies.
