### ISSUE TITLE
Overflow when using RandomSubset 

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#503]
TLC encounters an overflow error when evaluating the `RandomSubset` operator from the `Randomization` module with with a record set that is too big. For example, evaluating the following in the TLC REPL:

```
(tla+) RandomSubset(3, SUBSET [a:1..8, b:1..8])
util.Assert$TLCRuntimeException: Attempted to apply the operator overridden by the Java method
public static tlc2.value.impl.Value tlc2.module.Randomization.RandomSubset(tlc2.value.impl.Value,tlc2.value.impl.Value),
but it produced the following error:
Overflow when computing SubsetValue the number of elements in:
SUBSET { [a |-> 1, b |-> 1],
   [a |-> 1, b |-> 2],
   [a |-> 1, b |-> 3],
   [a |-> 1, b |-> 4],
   [a |-> 1, b |-> 5],
   [a |-> 1, b |-> 6],
   [a |-> 1, b |-> 7],
   [a |-> 1, b |-> 8],
   [a |-> 2, b |-> 1],
   [a |-> 2, b |-> 2],
   [a |-> 2, b |-> 3],
   [a |-> 2, b |-> 4],
   [a |-> 2, b |-> 5],
   [a |-> 2, b |-> 6],
   [a |-> 2, b |-> 7],
   [a |-> 2, b |-> 8],
   [a |-> 3, b |-> 1],
   [a |-> 3, b |-> 2],
   [a |-> 3, b |-> 3],
   [a |-> 3, b |-> 4],
   [a |-> 3, b |-> 5],
   [a |-> 3, b |-> 6],
   [a |-> 3, b |-> 7],
   [a |-> 3, b |-> 8],
   [a |-> 4, b |-> 1],
   [a |-> 4, b |-> 2],
   [a |-> 4, b |-> 3],
   [a |-> 4, b |-> 4],
   [a |-> 4, b |-> 5],
   [a |-> 4, b |-> 6],
   [a |-> 4, b |-> 7],
   [a |-> 4, b |-> 8],
   [a |-> 5, b |-> 1],
   [a |-> 5, b |-> 2],
   [a |-> 5, b |-> 3],
   [a |-> 5, b |-> 4],
   [a |-> 5, b |-> 5],
   [a |-> 5, b |-> 6],
   [a |-> 5, b |-> 7],
   [a |-> 5, b |-> 8],
   [a |-> 6, b |-> 1],
   [a |-> 6, b |-> 2],
   [a |-> 6, b |-> 3],
   [a |-> 6, b |-> 4],
   [a |-> 6, b |-> 5],
   [a |-> 6, b |-> 6],
   [a |-> 6, b |-> 7],
   [a |-> 6, b |-> 8],
   [a |-> 7, b |-> 1],
   [a |-> 7, b |-> 2],
   [a |-> 7, b |-> 3],
   [a |-> 7, b |-> 4],
   [a |-> 7, b |-> 5],
   [a |-> 7, b |-> 6],
   [a |-> 7, b |-> 7],
   [a |-> 7, b |-> 8],
   [a |-> 8, b |-> 1],
   [a |-> 8, b |-> 2],
   [a |-> 8, b |-> 3],
   [a |-> 8, b |-> 4],
   [a |-> 8, b |-> 5],
   [a |-> 8, b |-> 6],
   [a |-> 8, b |-> 7],
   [a |-> 8, b |-> 8] }
	at util.Assert.fail(Assert.java:33)
	at tlc2.value.impl.MethodValue.apply(MethodValue.java:176)
	at tlc2.value.impl.OpValue.eval(OpValue.java:25)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:1706)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:98)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1468)
	at tlc2.tool.impl.FastTool.eval(FastTool.java:91)
	at tlc2.tool.impl.Tool.eval(Tool.java:1364)
	at tlc2.REPL.processInput(REPL.java:121)
	at tlc2.REPL.runREPL(REPL.java:151)
	at tlc2.REPL.main(REPL.java:174)
```

From some investigation it looks like the error for this specific case arises from [the `size` call](https://github.com/tlaplus/tlaplus/blob/4aff6d2adb44fa381e75abc15858b5d5dd5be2c3/tlatools/org.lamport.tlatools/src/tlc2/value/impl/SubsetValue.java#L298) inside [SubsetValue.toSetEnum()](https://github.com/tlaplus/tlaplus/blob/4aff6d2adb44fa381e75abc15858b5d5dd5be2c3/tlatools/org.lamport.tlatools/src/tlc2/value/impl/SubsetValue.java#L294) which is [called from](https://github.com/tlaplus/tlaplus/blob/4aff6d2adb44fa381e75abc15858b5d5dd5be2c3/tlatools/org.lamport.tlatools/src/tlc2/value/impl/EnumerableValue.java#L59) EnumerableValue.getRandomSubset(). It looks like the issue manifests when the set size is greater than what can be handled by a 32 bit int e.g. `RandomSubset(3, SUBSET [a:1..8, b:1..4])` throws an error but `RandomSubset(3, SUBSET [a:1..8, b:1..3])` doesn't. 

Reproduced in TLC revision 4aff6d2.

**Comment by lemmy** [comment]
This is a minimal example in addition to http://discuss.tlapl.us/msg03777.html ?

**Comment by will62794** [comment]
Yeah. I originally ran into the error when working on a larger spec, and then produced this smaller repro.

**Comment by will62794** [comment]
Btw, for my specific use case, I realized that `RandomSetOfSubsets` probably works for avoiding this issue. My type correctness condition is something like 

```tla
r \in RandomSubset(3, SUBSET W)
```
where the cardinality of W is on the order of a few thousand elements. Using 

```tla
r \in RandomSetOfSubsets(3, 3, W)
```

 appears to avoid the overflow issue.

**Comment by lemmy** [comment]
TLC isn't smart enough to automatically rewrite `RandomSubset(3, SUBSET W)` to `RandomSetOfSubsets(3, 3, W)` and it's not worth changing.  Do you have any idea how others could be made aware of `RandomSetOfSubsets`?

**Comment by will62794** [comment]
It's made fairly clear in Lamport's [article](https://lamport.azurewebsites.net/tla/inductive-invariant.pdf), and probably addressed by a thorough read. Initially I started using `RandomSubset` since I thought that would suffice and after I ran into the overflow issues I thought I was stuck. Eventually I read through the article again and realized that `RandomSetOfSubsets` could probably solve my issue. I don't think it would be worth making any significant changes to these operators or their discoverability at this point since it's more or less an experimental and somewhat niche use case right now. If this technique for checking inductive invariance becomes more proven and generally useful, it might be worth giving TLC or the Toolbox more first class support for it, just to make the workflow more convenient. For example, I could imagine it being possible to have TLC automatically transform a normal `TypeOK` predicate into a "probabilistic" variant that can be used for invariance checking. That's a long way off, though, and by no means necessary especially until the use case is more common.

By the way, even though this use case can be solved by using `RandomSetOfSubsets`, do you think this GH issue it still a legitimate bug? I don't know enough about the implementation details of these operators to know if using `RandomSubset` for massive sets like this was ever expected to work. If my calculations were correct, in my spec I think I was trying to use  `RandomSubset` on a set with a cardinality around `2^5000`. I guess it's only necessary to have around 5000 bits to store the size of such a set, though, so not infeasible.

**Comment by lemmy** [comment]
Let's leave this issue open, but there is a lot that would have to change in the Value classes for it to generally work (i.e. more support to partially evaluate expressions symbolically/deferred evaluation/...).

**Comment by will62794** [comment]
Sounds good, thanks.
