### ISSUE TITLE
An internal error occurred during: "Azure". java.lang.NullPointerException

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#552]
http://discuss.tlapl.us/msg03988.html
http://discuss.tlapl.us/msg03989.html
http://discuss.tlapl.us/msg03990.html
http://discuss.tlapl.us/msg03991.html

![index](https://user-images.githubusercontent.com/88777/102123717-1cd97b80-3dfc-11eb-81c6-5e5eb7d2a061.png)

**Comment by lemmy** [comment]
Even if this problem gets addressed, https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1530 renders the Azure jclouds provider broken.  The only known-to-work cloud provider is PacketNet.

**Comment by 10227694** [comment]
Hi I am earnshaw on the tlaplus forum, I changed to another two clean computers and retried the test twice,then got the following result,

[ErrLog.txt](https://github.com/tlaplus/tlaplus/files/5692575/ErrLog.txt)

The above attachment  is the ~/.tlaplus/.metadata/.log

![image](https://user-images.githubusercontent.com/75654010/102155903-69ce5800-3eb7-11eb-819a-4a790836ad9e.png)
![image](https://user-images.githubusercontent.com/75654010/102156447-8dde6900-3eb8-11eb-98e2-6dc7d536b780.png)


[Model_2.zip](https://github.com/tlaplus/tlaplus/files/5692594/Model_2.zip)

**Comment by lemmy** [comment]
@10227694 Thanks for the additional information.  Unfortunately, I'm at a loss here; neither the screenshot of `eclipsec.exe` nor the attached `.log` file explain the `NullPointerException`. Does the NPE come up immediately after you launch model checking?  Do the other clouds such as PacketNet or AWS also produce an NPE?

**Comment by 10227694** [comment]
@lemmy   Thanks a lot,For Azure, NPEcomes after a usable node is chosen by Azure

![image](https://user-images.githubusercontent.com/75654010/102187003-5f7b8080-3eee-11eb-988f-f7a3a4928567.png)

For Amazon, not the NPE, but other type of Err listed below,  and PacketNet is not tested by me

![image](https://user-images.githubusercontent.com/75654010/102187328-d3b62400-3eee-11eb-9c87-85929281f526.png)
![image](https://user-images.githubusercontent.com/75654010/102187411-ea5c7b00-3eee-11eb-8af4-e268fc806ff4.png)

error running 1 node group(aws-ec2-52c6fa86-1864-4e0e-b7c7-cfea4999cfb6) location(us-east-1) image(ami-053295bb822a154ba) size(c3.8xlarge) options({inboundPorts=[22, 80, 443], scriptPresent=true, userDataCksum=2f4a740b})
Execution failures:

0 error[s]
Node failures:

1) NoSuchElementException on node us-east-1/i-05a5f4d239061e532:
java.util.NoSuchElementException: could not connect to any ip address port 22 on node {id=us-east-1/i-05a5f4d239061e532, providerId=i-05a5f4d239061e532, location={scope=ZONE, id=us-east-1a, description=us-east-1a, parent=us-east-1, iso3166Codes=[US-VA]}, group=aws-ec2-52c6fa86-1864-4e0e-b7c7-cfea4999cfb6, imageId=us-east-1/ami-053295bb822a154ba, os={family=ubuntu, arch=hvm, version=, description=ubuntu-images-us-east-1-release/bionic/20180814/hvm/instance-store/image.img.manifest.xml, is64Bit=true}, status=RUNNING[running], loginPort=22, hostname=ip-172-31-24-124, privateAddresses=[172.31.24.124], publicAddresses=[3.89.137.73], hardware={id=c3.8xlarge, providerId=c3.8xlarge, processors=[{cores=32.0, speed=3.375}], ram=61440, volumes=[{type=LOCAL, size=10.0, device=/dev/sda1, bootDevice=true, durable=false}, {type=LOCAL, size=320.0, device=/dev/sdb, bootDevice=false, durable=false}, {type=LOCAL, size=320.0, device=/dev/sdc, bootDevice=false, durable=false}], hypervisor=xen, supportsImage=Predicates.and(Predicates.alwaysTrue(),Predicates.or(requiresVirtualizationType(hvm),requiresVirtualizationType(paravirtual)),Predicates.alwaysTrue(),is64Bit())}, loginUser=ubuntu}
	at org.jclouds.compute.util.ConcurrentOpenSocketFinder.findOpenSocketOnNode(ConcurrentOpenSocketFinder.java:107)
	at org.jclouds.compute.functions.CreateSshClientOncePortIsListeningOnNode.apply(CreateSshClientOncePortIsListeningOnNode.java:66)
	at org.jclouds.compute.functions.CreateSshClientOncePortIsListeningOnNode.apply(CreateSshClientOncePortIsListeningOnNode.java:40)
	at org.jclouds.compute.callables.SudoAwareInitManager.init(SudoAwareInitManager.java:67)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSsh.init(RunScriptOnNodeAsInitScriptUsingSsh.java:64)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.init(RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.java:77)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.init(RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.java:38)
	at org.jclouds.compute.strategy.InitializeRunScriptOnNodeOrPlaceInBadMap.call(InitializeRunScriptOnNodeOrPlaceInBadMap.java:61)
	at org.jclouds.compute.strategy.InitializeRunScriptOnNodeOrPlaceInBadMap.call(InitializeRunScriptOnNodeOrPlaceInBadMap.java:34)
	at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.call(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:121)
	at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.call(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:50)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


1 error[s]
error running 1 node group(aws-ec2-52c6fa86-1864-4e0e-b7c7-cfea4999cfb6) location(us-east-1) image(ami-053295bb822a154ba) size(c3.8xlarge) options({inboundPorts=[22, 80, 443], scriptPresent=true, userDataCksum=2f4a740b})
Execution failures:

0 error[s]
Node failures:

1) NoSuchElementException on node us-east-1/i-05a5f4d239061e532:
java.util.NoSuchElementException: could not connect to any ip address port 22 on node {id=us-east-1/i-05a5f4d239061e532, providerId=i-05a5f4d239061e532, location={scope=ZONE, id=us-east-1a, description=us-east-1a, parent=us-east-1, iso3166Codes=[US-VA]}, group=aws-ec2-52c6fa86-1864-4e0e-b7c7-cfea4999cfb6, imageId=us-east-1/ami-053295bb822a154ba, os={family=ubuntu, arch=hvm, version=, description=ubuntu-images-us-east-1-release/bionic/20180814/hvm/instance-store/image.img.manifest.xml, is64Bit=true}, status=RUNNING[running], loginPort=22, hostname=ip-172-31-24-124, privateAddresses=[172.31.24.124], publicAddresses=[3.89.137.73], hardware={id=c3.8xlarge, providerId=c3.8xlarge, processors=[{cores=32.0, speed=3.375}], ram=61440, volumes=[{type=LOCAL, size=10.0, device=/dev/sda1, bootDevice=true, durable=false}, {type=LOCAL, size=320.0, device=/dev/sdb, bootDevice=false, durable=false}, {type=LOCAL, size=320.0, device=/dev/sdc, bootDevice=false, durable=false}], hypervisor=xen, supportsImage=Predicates.and(Predicates.alwaysTrue(),Predicates.or(requiresVirtualizationType(hvm),requiresVirtualizationType(paravirtual)),Predicates.alwaysTrue(),is64Bit())}, loginUser=ubuntu}
	at org.jclouds.compute.util.ConcurrentOpenSocketFinder.findOpenSocketOnNode(ConcurrentOpenSocketFinder.java:107)
	at org.jclouds.compute.functions.CreateSshClientOncePortIsListeningOnNode.apply(CreateSshClientOncePortIsListeningOnNode.java:66)
	at org.jclouds.compute.functions.CreateSshClientOncePortIsListeningOnNode.apply(CreateSshClientOncePortIsListeningOnNode.java:40)
	at org.jclouds.compute.callables.SudoAwareInitManager.init(SudoAwareInitManager.java:67)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSsh.init(RunScriptOnNodeAsInitScriptUsingSsh.java:64)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.init(RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.java:77)
	at org.jclouds.compute.callables.RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.init(RunScriptOnNodeAsInitScriptUsingSshAndBlockUntilComplete.java:38)
	at org.jclouds.compute.strategy.InitializeRunScriptOnNodeOrPlaceInBadMap.call(InitializeRunScriptOnNodeOrPlaceInBadMap.java:61)
	at org.jclouds.compute.strategy.InitializeRunScriptOnNodeOrPlaceInBadMap.call(InitializeRunScriptOnNodeOrPlaceInBadMap.java:34)
	at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.call(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:121)
	at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.call(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:50)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


1 error[s]

**Comment by lemmy** [comment]
When Amazon AWS ended our free tier, development and testing on the AWS provided stopped.
