### ISSUE TITLE
Toolbox fails to launch on macOS Sierra

### ISSUE THREAD

**Issue by boneskull** [tlaplus/tlaplus#56]
I downloaded v1.5.3, opened the archive, and double-clicked on `TLA+ Toolbox.app`.  The splash came up, but then I received an error alert referring me to a logfile, the contents of which are [here](https://gist.github.com/boneskull/e167c005625b2a86454e2f052933eb2f).

I should note that the path noted in the log does not actually exist. 
 `/var/folders/7f/7vr9hv5j35zd_0k42n8m4xhw0000gs/T/AppTranslocation/C0F121AC-80E0-4D2B-B2D6-BD2E6600F10F/d/TLA+ Toolbox.app/Contents/MacOS` exists, but that directory only contains a `toolbox` directory.  There is no `workspace` directory.  

**Workaround**: Launching the app from my console via `/Applications/TLA+\ Toolbox.app/Contents/MacOS/toolbox` *does* launch the program, however.

**Comment by lemmy** [comment]
Hi, I can reproduce the behavior when I double-click TLA+ Toolbox.app in the Downloads/ folder. However, if the TLA+ Toolbox.app is first moved to /Applications manually, it opens correctly. As far as I remember, this is a security mechanism of macOS Sierra, such that it sandboxes applications that are run from Downloads/. The Toolbox does not support running in this sandbox.

**Comment by boneskull** [comment]
moving it to /Applications doesn't seem to have any positive effect for me

**Comment by lemmy** [comment]
Which version of macOS are you on? I'm on 10.12.5.

**Comment by boneskull** [comment]
same

**Comment by boneskull** [comment]
I have SIP disabled, as well.  can I verify expected permissions?  I've had problems from time-to-time with various unarchiving tools and permissions on the extracted files

**Comment by lemmy** [comment]
This [issue](https://github.com/potionfactory/LetsMove/issues/56#issue-162975492) related to a security feature of macOS Sierra called "Translocation" or "Gatekeeper Path Randomization" seems to describe what you are seeing. The gist appears to be, that you have to use the Finder to move the Toolbox to /Applications, which disables Translocation.

Translocation is apparently active for all apps launched from the Downloads/ folder. A Translocation is read-only, which stops the Toolbox from launching.

**Comment by enriquefynn** [comment]
You need to remove the quarantine flag from the directory, you can do it with:
`xattr -dr com.apple.quarantine TLA+\ Toolbox.app`

**Comment by boneskull** [comment]
Thanks, didn't know this.  I'll try it now.

**Comment by boneskull** [comment]
Yes, it works if I use **Finder.app** to move the file.  But I normally use [Cocoatech's Path Finder](https://cocoatech.com/), which doesn't seem to remove the "quarantined" flag!

**Comment by bitemyapp** [comment]
Moving with Finder.app and `xattr -dr com.apple.quarantine TLA+\ Toolbox.app` didn't seem to fix TLA+ on High Sierra for me.

**Comment by bitemyapp** [comment]
Here's the error log — missing libraries?

[tla_error.log](https://github.com/tlaplus/tlaplus/files/1361744/tla_error.log)

**Comment by lemmy** [comment]
@bitemyapp Please install Java JDK 1.8 for macOS from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by bitemyapp** [comment]
@lemmy I think I had the JRE rather than the JDK. I'll try this, thank you!

**Comment by tancorko** [comment]
/.toolbox
java.lang.module.FindException: Module java.se.ee not found

But JDK is installed.

**Comment by lemmy** [comment]
@tancorko Which version of the JDK (java -version)?

**Comment by tancorko** [comment]
@lemmy 8 update 192 (build 1.8.0_192-b12)

**Comment by lemmy** [comment]
@tancorko That should work fine. Can you try to hardwire the Toolbox to a specific JVM following these [instructions](https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Mac_OS_X_Example)? Just replace "eclipse" with "toolbox".

**Comment by tancorko** [comment]
@lemmy Yes, it works. Thanks a lot!

**Comment by jasonkrasavage** [comment]
Where in the .ini file do I add the "-vm" and then the path, which for me is "/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java" if I am interpreting the tutorial correctly?

@lemmy could you lend a hand? Don't want to open a new support threat because my problem is so similar. I've already added the "-clean" right before "-vmargs" and still have the same issue: error and failure to start upon launching.

**Comment by lemmy** [comment]
@jasonkrasavage Below is how it is done on Linux which is almost identical to macOS.

```
-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.800.v20180827-1352
--launcher.defaultAction
openFile
-name
TLA+ Toolbox
--launcher.GTK_version
2
-vm
/usr/lib/jvm/java-8-oracle/bin/
-vmargs
--add-modules=java.se.ee
-XX:+IgnoreUnrecognizedVMOptions
-Xmx1000m
-Dorg.eclipse.equinox.http.jetty.http.port=10996
-Dosgi.splashPath=platform:/base/
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/.tlaplus/
```

**Comment by jasonkrasavage** [comment]
Believe I have that correct then, what is my issue?

> -startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.551.v20171108-1834
--launcher.defaultAction
openFile
-name
TLA+ Toolbox
-vm
/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java
-clean
-vmargs
--add-modules=java.se.ee
-XX:+IgnoreUnrecognizedVMOptions
-Xmx1000m
-Dorg.eclipse.equinox.http.jetty.http.port=10996
-Dosgi.splashPath=platform:/base/
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/.tlaplus/
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts

**Comment by jasonkrasavage** [comment]
Log file: 

`!SESSION 2018-11-11 12:33:55.693 -----------------------------------------------
eclipse.buildId=1.5.7
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/jasonkrasavage/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/jasonkrasavage/.eclipse_keyring

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2018-11-11 12:33:57.805
!MESSAGE TLA+ Toolbox started without arguments.

!ENTRY org.eclipse.osgi 4 0 2018-11-11 12:33:58.184
!MESSAGE Application error
!STACK 1
The Toolbox failed to launch because of an unexpected error. Please try to launch the Toolbox with the "-clean" parameter.
If "-clean" does not fix the problem, please open a bug and attach the .log file.

org.lamport.tla.toolbox.Application$2: org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.lamport.tla.toolbox.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.lamport.tla.toolbox.Application.start(Application.java:141)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 22 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 24 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-11-11 12:33:58.190
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStop(Module.java:634)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more
`
