### ISSUE TITLE
Preference "Add Directory..." do nothing  (SWTError: No more handles)

### ISSUE THREAD

**Issue by mrLSD** [tlaplus/tlaplus#623]
When I open `Preferences -> TLA+ Preferences`
And click: `Add Directory...`
Nothin happens. 

```
toolbox - latest
OS: Ubuntu 16.04
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

```

**Comment by lemmy** [comment]
On Ubuntu 20.04, "Add Directory..." opens the native directory chooser.  What is your Window Manager?  Also, `latest` is latest nightly or 1.7.1?

**Comment by mrLSD** [comment]
`toolbox v1.7.1`
Ubuntu 16.04, Unity

**Comment by lemmy** [comment]
Also, please check the `.log` file in `$HOME/.tlaplus/.metadata/` for anything suspicious.

**Comment by mrLSD** [comment]
```
!SESSION 2021-05-13 21:32:28.115 -----------------------------------------------
eclipse.buildId=1.7.1
java.version=14.0.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2021-05-13 21:32:29.293
!MESSAGE TLA+ Toolbox started without arguments.

!ENTRY org.eclipse.ui 4 0 2021-05-13 21:32:58.412
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
	at org.eclipse.swt.widgets.DirectoryDialog.openNativeChooserDialog(DirectoryDialog.java:139)
	at org.eclipse.swt.widgets.DirectoryDialog.open(DirectoryDialog.java:123)
	at org.lamport.tla.toolbox.ui.preference.LibraryPathComposite.getDirectory(LibraryPathComposite.java:398)
	at org.lamport.tla.toolbox.ui.preference.LibraryPathComposite$4.widgetSelected(LibraryPathComposite.java:174)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.lamport.tla.toolbox.Application.start(Application.java:141)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by lemmy** [comment]
Can you check https://stackoverflow.com/questions/64647972/java-eclipse-2020-09-import-launch-configuration-unhandled-event-loop-excepti

**Comment by mrLSD** [comment]
So there is only one way update to gtk 3.20. But it can break the system.

How to put that path config property manually, probably to the config file?

**Comment by lemmy** [comment]
With something broken as basic as this, you will probably run into all sorts of issues, even if you manage to manually pass the `TLA-Library` sysproperty to TLC.  If you can't risk upgrading gtk, you are probably better off grabbing an older Toolbox release that works with older versions of gtk.  Alternatively, you can try out the [TLA+ VSCode extension](https://github.com/alygin/vscode-tlaplus), which covers a subset of the Toolbox features.
Unfortunately, we don't have the resources to support more than just the most recent versions of Win10, Ubuntu, and macOS (that's already a stretch). :-(
