### ISSUE TITLE
Error when setup eclipse IDE with Oomph.

### ISSUE THREAD

**Issue by Jack1106012623** [tlaplus/tlaplus#740]
I followed instructions of [ide/README.md](https://github.com/tlaplus/tlaplus/blob/master/general/ide/README.md), choosing Eclipse Platform "2020-12" and Project "TLA+".  The installation successed but after Eclipse restarts the workspace remains empty and the progress diaglog is blank. There're some logs of the file `.metadata/.log` at the end. 

I found that if TLA+ project were selected to provision, version of the installed Eclipse would be "2021-12". I tried installing version "2020-12" and then import TLA+ project, the version changed to "2021-12" after import. Maybe the version change when importing TLA+ project cause this problem, but I don't know how to solve it. 
Could you tell me how to fix that, please?

Thank you very much.

```
!ENTRY org.eclipse.osgi 4 0 2022-06-22 17:42:20.196
!MESSAGE An error occurred while automatically activating bundle org.eclipse.oomph.p2.core (256).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.oomph.p2.internal.core.P2CorePlugin$Implementation.start() of bundle org.eclipse.oomph.p2.core.
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:828)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
    at org.eclipse.osgi.container.Module.doStart(Module.java:605)
    ...
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
Caused by: java.lang.NoSuchMethodError: 'java.util.HashMap org.eclipse.core.internal.runtime.AdapterManager.getFactories()'
    at org.eclipse.oomph.p2.internal.core.P2CorePlugin$Implementation.start(P2CorePlugin.java:145)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
    ... 65 more
Root exception:
java.lang.NoSuchMethodError: 'java.util.HashMap org.eclipse.core.internal.runtime.AdapterManager.getFactories()'
    at org.eclipse.oomph.p2.internal.core.P2CorePlugin$Implementation.start(P2CorePlugin.java:145)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
    ...
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
```

**Comment by Jack1106012623** [comment]
I finally solved my problem. Perhaps the latest version e4 and m2e (maybe one of the two) in P2 Director require the 2021Eclipse. I removed the two requirements in TlA.setup and later manually installed e4 and m2e in 2020Eclipse, which solved my problem and the projects was successfully imported. By the way, I also encountered '***.feature.group of rcptt could not be resolved'(I forgot the full description) but I didn't delete rcp requirement and repository. So same as e3 and m2e, I deleted the rcptt requirement in TLA.setup and installed it later successfully using the same repository https://download.eclipse.org/rcptt/release/2.5.1/repository/.
