### ISSUE TITLE
TLC unexpected exception on any TLA spec

### ISSUE THREAD

**Issue by houseofwealth** [tlaplus/tlaplus#762]
## Description

Trying to run TLC on _any_ TLA spec (including ones that used to run just fine) causes TLC to throw an unexpected exception:

## Expected Behavior

TLC should run normally and report any model checking errors it finds

## Actual Behavior

```
unsuccessfully trying to load custom FPSet class: tlc2.tool.fp.OffHeapDiskFPSet
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.util.concurrent.ExecutionException
: java.lang.NullPointerException
```

and in the User Ouput window:

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at tlc2.tool.fp.FPSetFactory.loadImplementation(FPSetFactory.java:206)
	at tlc2.tool.fp.FPSetFactory.getFPSet(FPSetFactory.java:109)
	at tlc2.tool.fp.MultiFPSet.getNestedFPSets(MultiFPSet.java:68)
	at tlc2.tool.fp.MultiFPSet.<init>(MultiFPSet.java:61)
	at tlc2.tool.fp.FPSetFactory.getFPSet(FPSetFactory.java:105)
	at tlc2.tool.fp.FPSetFactory$1.call(FPSetFactory.java:136)
	at tlc2.tool.fp.FPSetFactory$1.call(FPSetFactory.java:1)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError
	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
	at jdk.unsupported/sun.misc.Unsafe.allocateMemory(Unknown Source)
	at tlc2.tool.fp.LongArray.<init>(LongArray.java:79)
	at tlc2.tool.fp.OffHeapDiskFPSet.<init>(OffHeapDiskFPSet.java:138)
	... 16 more
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at tlc2.tool.fp.FPSetFactory.loadImplementation(FPSetFactory.java:206)
	at tlc2.tool.fp.FPSetFactory.getFPSet(FPSetFactory.java:109)
	at tlc2.tool.fp.MultiFPSet.getNestedFPSets(MultiFPSet.java:68)
	at tlc2.tool.fp.MultiFPSet.<init>(MultiFPSet.java:61)
	at tlc2.tool.fp.FPSetFactory.getFPSet(FPSetFactory.java:105)
	at tlc2.tool.fp.FPSetFactory$1.call(FPSetFactory.java:136)
	at tlc2.tool.fp.FPSetFactory$1.call(FPSetFactory.java:1)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError
	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
	at jdk.unsupported/sun.misc.Unsafe.allocateMemory(Unknown Source)
	at tlc2.tool.fp.LongArray.<init>(LongArray.java:79)
	at tlc2.tool.fp.OffHeapDiskFPSet.<init>(OffHeapDiskFPSet.java:138)
	... 16 more
```

## Steps to Reproduce
N/A

## Steps Taken to Fix

Tried on multiple TLA specs including past ones that used to work. I am not out of memory despite the apparent warning

## Possible Fix

No

## Your Environment

 - TLC version: 1.7.1 and 1.8.0 (tried both)
 - Toolbox version: 1.71. and 1.8.0
 - Operating System:  Windows 10

**Comment by lemmy** [comment]
What's your Java version?

**Comment by houseofwealth** [comment]
$ java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Comment by houseofwealth** [comment]
Is it possible that Toolbox is using some other version of Java and that's incompatible with TLC? How can I see which version Toolbox is running on? Just brainstorming ways in which I can debug this

**Comment by lemmy** [comment]
The Toolbox comes indeed with its [own](https://github.com/lemmy/eclipse-jdk-bundles), a compatible version of Java.

**Comment by lemmy** [comment]
Can you try running command-line TLC with Java 11?

**Comment by houseofwealth** [comment]
Well, so that _did_ work. Initially that was also giving me an :insufficient memory" error message but after I shut down the toolbox and another large app, it was able to run. Now when I restart the toolbox it seems to be fine. Its odd because when I originally reported the problem, Task Manager showed that I had 25% memory available out of 16GB, so I don't know why it was saying that. Anyway seems fine now. Thanks

**Comment by houseofwealth** [comment]
The problem reappeared. I was about to look into it but my machine was scheduled for a reboot, so I'll have to wait until the problem reappears. It may be related to this https://help.vocareum.com/en/articles/3659006-jvm-insufficient-memory-error

**Comment by ahelwer** [comment]
This is probably caused by LongArray trying to allocate a bunch of native memory using `sun.misc.Unsafe` when there isn't sufficient memory to do so. It will probably be fixed by upgrading to the new Java FFM API in #951, which I hope has a nicer error for this.

**Comment by lemmy** [comment]
@houseofwealth Please reopen if you're still affected.
