### ISSUE TITLE
Prop == Init => <>[](X) fails in seemingly unreasonable way; often gets stuck if using workers

### ISSUE THREAD

**Issue by eras** [tlaplus/tlaplus#773]
## Description

I assume this issue has not been noticed, as the linked issue does not have a mention of it.

I noticed with a colleague that this kind of property fails [in the model](https://github.com/eras/tla-issue) with TLC version ca5ad64 (so the "1.8.0" version):

```
EventuallyAllFilesAreForeverTransferred ==
   Init => <>[](AllLocalFilesAreTransferredAsInRemote /\ NoTransfers)
```

whereas substituting `Init` with either a boolean work as expected, as does removing `Init =>` altogether. This is probably not the general pattern yet, but depends on the definitions of the values, in particular `Init` (this is just a guess).

The interesting thing is that this works in commit 74911efbe197b141fc7245ef7151dfa841c579ab but the fails with the next commit b04167104107e7130e3ae4c32e018e1d6e4e279b. The issue that the commit fixes is https://github.com/tlaplus/tlaplus/issues/710 .

I realize the reproduction spec is way too large to analyze a bug properly, but I hope at least the exact commit should be helpful. I'll try to minimize the issue at some later point. Report first, fine-tune later?

TLC also often gets stuck if checking this model and using workers.

## Expected Behavior

I expect the property to behave the same without the implication as with it. If the part `Init =>` is removed and only the temporal formula remains the property holds according to TLC.

## Actual Behavior

Running the checker results in this:

```
% tlc Main.tla -config Minimal.cfg
TLC2 Version 2.18 of Day Month 20?? (rev: ca5ad64)
Running breadth-first search Model-Checking with fp 9 and seed 6600409799035981577 with 1 worker on 24 cores with 14299MB heap and 64MB offheap memory [pid: 2666848] (Linux 5.8.0-1aiee0+ amd64, Debian 11.0.12 x86_64, MSBDiskFPSet, DiskStateQueue).
...redacted...
Starting... (2022-12-10 16:41:13)
Implied-temporal checking--satisfiability problem has 2 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2022-12-10 16:41:13.
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ chan_local_to_dialog = <<>>
/\ dialog_state = "closed"
/\ remote_state = [listing_files |-> FALSE, listed_file_index |-> 0]
/\ remote_files = <<[name |-> <<"filename", 1>>, size |-> 0]>>
/\ local_state = "idle"
/\ local_transfers = <<<<>>>>
/\ local_files = <<<<>>>>
/\ chan_remote_to_local = <<>>
/\ chan_local_to_remote = <<>>
/\ remote_send_queue = <<>>

2 states generated, 2 distinct states found, 1 states left on queue.
The depth of the complete state graph search is 2.
Finished in 00s at (2022-12-10 16:41:13)
```

This happens often if using workers:

```
% tlc Main.tla -config Minimal.cfg -workers auto
TLC2 Version 2.18 of Day Month 20?? (rev: ca5ad64)
Running breadth-first search Model-Checking with fp 55 and seed 1309556997007023961 with 24 workers on 24 cores with 14299MB heap and 64MB offheap memory [pid: 2667805] (Linux 5.8.0-1aiee0+ amd64, Debian 11.0.12 x86_64, MSBDiskFPSet, DiskStateQueue).
...redacted...
Starting... (2022-12-10 16:35:13)
Implied-temporal checking--satisfiability problem has 2 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2022-12-10 16:35:13.
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ chan_local_to_dialog = <<>>
/\ dialog_state = "closed"
/\ remote_state = [listing_files |-> FALSE, listed_file_index |-> 0]
/\ remote_files = <<[name |-> <<"filename", 1>>, size |-> 0]>>
/\ local_state = "idle"
/\ local_transfers = <<<<>>>>
/\ local_files = <<<<>>>>
/\ chan_remote_to_local = <<>>
/\ chan_local_to_remote = <<>>
/\ remote_send_queue = <<>>

Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

```
And then it's just stuck there. Pressing ctrl-4 to gives:
```
^\2022-12-10 16:39:06
Full thread dump OpenJDK 64-Bit Server VM (11.0.12+7-post-Debian-2deb10u1 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007f7ac0001d60, length=20, elements={
0x00007f7c10015800, 0x00007f7c1005c000, 0x00007f7c1005e000, 0x00007f7c10065000,
0x00007f7c10067000, 0x00007f7c10069800, 0x00007f7c1006b800, 0x00007f7c1006d800,
0x00007f7c100b1800, 0x00007f7b88102800, 0x00007f7b88105800, 0x00007f7b88109800,
0x00007f7b8817e800, 0x00007f7c102c2800, 0x00007f7c103ff000, 0x00007f7c10402800,
0x00007f7c10404800, 0x00007f7c10420000, 0x00007f7c10422000, 0x00007f7c10426000
}

"main" #1 prio=5 os_prio=0 cpu=469,48ms elapsed=233,94s tid=0x00007f7c10015800 nid=0x28a706 in Object.wait()  [0x00007f7c147d9000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x00000006b6d27e10> (a tlc2.tool.Worker)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1300)
	- waiting to re-lock in wait() <0x00000006b6d27e10> (a tlc2.tool.Worker)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1375)
	at tlc2.tool.AbstractChecker.runTLC(AbstractChecker.java:495)
	at tlc2.tool.ModelChecker.modelCheckImpl(ModelChecker.java:243)
	at tlc2.tool.AbstractChecker.modelCheck(AbstractChecker.java:580)
	at tlc2.TLC.process(TLC.java:1200)
	at tlc2.TLC.main(TLC.java:352)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0,46ms elapsed=233,93s tid=0x00007f7c1005c000 nid=0x28a709 waiting on condition  [0x00007f7bcba6a000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.12/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.12/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.12/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0,14ms elapsed=233,93s tid=0x00007f7c1005e000 nid=0x28a70a in Object.wait()  [0x00007f7bcb969000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000412a04ac0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000412a04ac0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.12/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0,09ms elapsed=233,93s tid=0x00007f7c10065000 nid=0x28a70b waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0,03ms elapsed=233,93s tid=0x00007f7c10067000 nid=0x28a70c runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=395,96ms elapsed=233,93s tid=0x00007f7c10069800 nid=0x28a70d waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #14 daemon prio=9 os_prio=0 cpu=247,74ms elapsed=233,93s tid=0x00007f7c1006b800 nid=0x28a70e waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #18 daemon prio=9 os_prio=0 cpu=0,03ms elapsed=233,93s tid=0x00007f7c1006d800 nid=0x28a70f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #19 daemon prio=8 os_prio=0 cpu=0,50ms elapsed=233,91s tid=0x00007f7c100b1800 nid=0x28a711 in Object.wait()  [0x00007f7bcac68000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000412a1c7a0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000412a1c7a0> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.12/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.12/InnocuousThread.java:134)

"RMI TCP Accept-0" #26 daemon prio=5 os_prio=0 cpu=0,22ms elapsed=233,47s tid=0x00007f7b88102800 nid=0x28a71d runnable  [0x00007f7bc9954000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(java.base@11.0.12/Native Method)
	at java.net.AbstractPlainSocketImpl.accept(java.base@11.0.12/AbstractPlainSocketImpl.java:458)
	at java.net.ServerSocket.implAccept(java.base@11.0.12/ServerSocket.java:565)
	at java.net.ServerSocket.accept(java.base@11.0.12/ServerSocket.java:533)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(java.rmi@11.0.12/TCPTransport.java:394)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(java.rmi@11.0.12/TCPTransport.java:366)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

"RMI Reaper" #27 prio=5 os_prio=0 cpu=0,13ms elapsed=233,47s tid=0x00007f7b88105800 nid=0x28a71e in Object.wait()  [0x00007f7bc9853000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000412a1b380> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000412a1b380> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:176)
	at sun.rmi.transport.ObjectTable$Reaper.run(java.rmi@11.0.12/ObjectTable.java:349)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

"RMI GC Daemon" #28 daemon prio=2 os_prio=0 cpu=0,20ms elapsed=233,47s tid=0x00007f7b88109800 nid=0x28a71f in Object.wait()  [0x00007f7bc9552000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000412a5c4e8> (a sun.rmi.transport.GC$LatencyLock)
	at sun.rmi.transport.GC$Daemon.run(java.rmi@11.0.12/GC.java:126)
	- waiting to re-lock in wait() <0x0000000412a5c4e8> (a sun.rmi.transport.GC$LatencyLock)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.12/InnocuousThread.java:134)

"ForkJoinPool.commonPool-worker-51" #29 daemon prio=5 os_prio=0 cpu=0,98ms elapsed=233,37s tid=0x00007f7b8817e800 nid=0x28a732 waiting on condition  [0x00007f7bc832f000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000006b11689b0> (a java.util.concurrent.ForkJoinPool)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.12/LockSupport.java:194)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.12/ForkJoinPool.java:1628)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.12/ForkJoinWorkerThread.java:183)

"TLCWorkerThread-001" #31 prio=5 os_prio=0 cpu=10,02ms elapsed=233,31s tid=0x00007f7c102c2800 nid=0x28a734 waiting for monitor entry  [0x00007f7b23ffe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:205)
	- locked <0x0000000412a146a0> (a tlc2.tool.ModelChecker)
	at tlc2.tool.Worker.run(Worker.java:135)

"TLCWorkerThread-002" #32 prio=5 os_prio=0 cpu=7,74ms elapsed=233,31s tid=0x00007f7c103ff000 nid=0x28a735 waiting for monitor entry  [0x00007f7b23efd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.Worker.run(Worker.java:93)
	- waiting to lock <0x0000000412a146a0> (a tlc2.tool.ModelChecker)

"TLCWorkerThread-004" #34 prio=5 os_prio=0 cpu=7,53ms elapsed=233,31s tid=0x00007f7c10402800 nid=0x28a737 waiting for monitor entry  [0x00007f7b23cfb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

"TLCWorkerThread-005" #35 prio=5 os_prio=0 cpu=7,99ms elapsed=233,31s tid=0x00007f7c10404800 nid=0x28a738 waiting for monitor entry  [0x00007f7b23bfa000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

"TLCWorkerThread-020" #50 prio=5 os_prio=0 cpu=5,55ms elapsed=233,31s tid=0x00007f7c10420000 nid=0x28a747 waiting for monitor entry  [0x00007f7b22ceb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

"TLCWorkerThread-021" #51 prio=5 os_prio=0 cpu=6,88ms elapsed=233,31s tid=0x00007f7c10422000 nid=0x28a748 waiting for monitor entry  [0x00007f7b22bea000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

"TLCWorkerThread-023" #53 prio=5 os_prio=0 cpu=10,02ms elapsed=233,31s tid=0x00007f7c10426000 nid=0x28a74a waiting for monitor entry  [0x00007f7b229e8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:716)
	- waiting to lock <0x0000000412a146a0> (a tlc2.tool.ModelChecker)
	- locked <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

"VM Thread" os_prio=0 cpu=26,73ms elapsed=233,93s tid=0x00007f7c10059000 nid=0x28a708 runnable  

"ParGC Thread#0" os_prio=0 cpu=10,10ms elapsed=233,94s tid=0x00007f7c1002d800 nid=0x28a707 runnable  

"ParGC Thread#1" os_prio=0 cpu=13,90ms elapsed=233,47s tid=0x00007f7bc4031000 nid=0x28a720 runnable  

"ParGC Thread#2" os_prio=0 cpu=11,44ms elapsed=233,47s tid=0x00007f7bc4032800 nid=0x28a721 runnable  

"ParGC Thread#3" os_prio=0 cpu=12,09ms elapsed=233,47s tid=0x00007f7bc4034000 nid=0x28a722 runnable  

"ParGC Thread#4" os_prio=0 cpu=11,35ms elapsed=233,47s tid=0x00007f7bc4035800 nid=0x28a723 runnable  

"ParGC Thread#5" os_prio=0 cpu=11,77ms elapsed=233,47s tid=0x00007f7bc4037000 nid=0x28a724 runnable  

"ParGC Thread#6" os_prio=0 cpu=5,34ms elapsed=233,47s tid=0x00007f7bc4039000 nid=0x28a725 runnable  

"ParGC Thread#7" os_prio=0 cpu=11,71ms elapsed=233,47s tid=0x00007f7bc403a800 nid=0x28a726 runnable  

"ParGC Thread#8" os_prio=0 cpu=12,85ms elapsed=233,47s tid=0x00007f7bc403c800 nid=0x28a727 runnable  

"ParGC Thread#9" os_prio=0 cpu=11,71ms elapsed=233,47s tid=0x00007f7bc403e800 nid=0x28a728 runnable  

"ParGC Thread#10" os_prio=0 cpu=10,76ms elapsed=233,47s tid=0x00007f7bc4040000 nid=0x28a729 runnable  

"ParGC Thread#11" os_prio=0 cpu=10,97ms elapsed=233,47s tid=0x00007f7bc4042000 nid=0x28a72a runnable  

"ParGC Thread#12" os_prio=0 cpu=9,90ms elapsed=233,47s tid=0x00007f7bc4043800 nid=0x28a72b runnable  

"ParGC Thread#13" os_prio=0 cpu=11,87ms elapsed=233,47s tid=0x00007f7bc4045800 nid=0x28a72c runnable  

"ParGC Thread#14" os_prio=0 cpu=9,94ms elapsed=233,47s tid=0x00007f7bc4047000 nid=0x28a72d runnable  

"ParGC Thread#15" os_prio=0 cpu=12,28ms elapsed=233,47s tid=0x00007f7bc4049000 nid=0x28a72e runnable  

"ParGC Thread#16" os_prio=0 cpu=8,22ms elapsed=233,47s tid=0x00007f7bc404b000 nid=0x28a72f runnable  

"ParGC Thread#17" os_prio=0 cpu=6,68ms elapsed=233,47s tid=0x00007f7bc404c800 nid=0x28a730 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=66,38ms elapsed=233,92s tid=0x00007f7c100aa000 nid=0x28a710 waiting on condition  

JNI global refs: 38, weak refs: 0


Found one Java-level deadlock:
=============================
"TLCWorkerThread-001":
  waiting to lock monitor 0x00007f7b88182280 (object 0x0000000412cfb4f0, a tlc2.tool.liveness.OrderOfSolution),
  which is held by "TLCWorkerThread-023"
"TLCWorkerThread-023":
  waiting to lock monitor 0x00007f7b74004e80 (object 0x0000000412a146a0, a tlc2.tool.ModelChecker),
  which is held by "TLCWorkerThread-001"

Java stack information for the threads listed above:
===================================================
"TLCWorkerThread-001":
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:639)
	- waiting to lock <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:205)
	- locked <0x0000000412a146a0> (a tlc2.tool.ModelChecker)
	at tlc2.tool.Worker.run(Worker.java:135)
"TLCWorkerThread-023":
	at tlc2.tool.liveness.LiveCheck$TableauLiveChecker.addNextState(LiveCheck.java:716)
	- waiting to lock <0x0000000412a146a0> (a tlc2.tool.ModelChecker)
	- locked <0x0000000412cfb4f0> (a tlc2.tool.liveness.OrderOfSolution)
	at tlc2.tool.liveness.LiveCheck.addNextState(LiveCheck.java:124)
	at tlc2.tool.Worker.doNextCheckLiveness(Worker.java:186)
	at tlc2.tool.Worker.run(Worker.java:135)

Found 1 deadlock.

Heap
 PSYoungGen      total 300544K, used 117178K [0x00000006b0e00000, 0x00000006c5d00000, 0x0000000800000000)
  eden space 258048K, 45% used [0x00000006b0e00000,0x00000006b806e8f0,0x00000006c0a00000)
  from space 42496K, 0% used [0x00000006c0a00000,0x00000006c0a00000,0x00000006c3380000)
  to   space 42496K, 0% used [0x00000006c3380000,0x00000006c3380000,0x00000006c5d00000)
 ParOldGen       total 687104K, used 11818K [0x0000000412a00000, 0x000000043c900000, 0x00000006b0e00000)
  object space 687104K, 1% used [0x0000000412a00000,0x000000041358abd8,0x000000043c900000)
 Metaspace       used 17194K, capacity 17708K, committed 17920K, reserved 1064960K
  class space    used 1753K, capacity 1936K, committed 2048K, reserved 1048576K
```

## Steps to Reproduce
1. Check out the repository at https://github.com/eras/tla-issue
2. Install the latest version of TLC, or at least version b04167104107e7130e3ae4c32e018e1d6e4e279b
3. Arrange `tlc` to invoke TLC checker, e.g. `alias tlc='java -XX:+IgnoreUnrecognizedVMOptions -XX:+UseParallelGC -cp /some/directory/tla2tools.jar tlc2.TLC'`
4. `cd tla-issue; tlc Main.tla -config Minimal.cfg`
5. Witness property check failure, and maybe TLC getting stuck

## Steps Taken to Fix

I tried different variations of the property; replacing `Init` with a literal boolean value, or removing `Init =>` altogether, and those work as expected.

Clearly we don't need `Init =>` here at all, but it shouldn't break it either, so I used `git bisect` with the test case to find the version that broke it.

We only noticed this issue as we had different versions of TLC installed, one where it worked and one where it didn't.

## Possible Fix
No idea of a possible fix, other than reverting the commit :).

## Your Environment
- TLC version: reproduced in b04167104107e7130e3ae4c32e018e1d6e4e279b, ca5ad64, e7c0763, and several others with `git bisect`
- Toolbox version: did not use toolbox itself, only TLC from it
- Operating System: Arch and Debian
- Java version: openjdk 11.0.12 2021-07-20

**Comment by lemmy** [comment]
Thanks for the detailed bug report that gave me a hunch what the source of the deadlock might be.

**Comment by lemmy** [comment]
@eras Please test f84d85b locally.  I would have liked to provide a nightly build, but the Github action is failing for some unrelated reason.

**Comment by eras** [comment]
At first I was unable to compile it due to this error:
```
    [javac] /home/flux/projects/2022/TLA+/ext/tlaplus/tlatools/org.lamport.tlatools/src/tla2sany/semantic/SemanticNode.java:306: error: cannot infer type arguments for ExplorerVisitor<T>
    [javac] 	final ExplorerVisitor<Boolean> visitor = new ExplorerVisitor<>() {
    [javac] 	                                                            ^
    [javac]   reason: '<>' with anonymous inner classes is not supported in -source 8
    [javac]     (use -source 9 or higher to enable '<>' with anonymous inner classes)
    [javac]   where T is a type-variable:
    [javac]     T extends Object declared in class ExplorerVisitor
```

So I did the obvious change (though maybe some cleanin op would have worked as well, but I'm not well familiar with Java development), and then it compiles and worked without issue:

```
Starting... (2022-12-12 21:12:28)
Implied-temporal checking--satisfiability problem has 2 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2022-12-12 21:12:28.
Progress(15) at 2022-12-12 21:12:28: 54 states generated, 34 distinct states found, 0 states left on queue.
Checking 2 branches of temporal properties for the complete state space with 68 total distinct states at (2022-12-12 21:12:28)
Finished checking temporal properties in 00s at 2022-12-12 21:12:28
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 3.7E-17
54 states generated, 34 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 15.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 2 and the 95th percentile is 2).
Finished in 00s at (2022-12-12 21:12:28)
```

Thanks!
