### ISSUE TITLE
IDE setup instructions need updating

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#851]
The current [IDE setup instructions](https://github.com/tlaplus/tlaplus/blob/193da949dc8eb783a2683f01f3a54da93fd85a39/general/ide/README.md) are not working for me. They may be out of date. It is also possible that my machine has some bizarre (mis)configuration that is preventing it from succeeding.

My setup:
 - MacOS 12.6.8, M1 (aarch64)
 - Eclipse Installer (Oomph) 1.31.0 Build 329, downloaded from https://www.eclipse.org/downloads/packages/installer

Notes about the current instructions:

The Oomph link https://wiki.eclipse.org/Eclipse_Installer is a wiki page with a big warning about the wiki being deprecated. I believe the new link is https://www.eclipse.org/downloads/packages/installer.

Eclipse platform 2020-12 is no longer available. The earliest version available is 2021-12:

![Screen Shot 2023-12-01 at 2 28 41 PM](https://github.com/tlaplus/tlaplus/assets/1393639/99c31e30-cf36-4c29-9057-f496b84af2e7)

Although, the installer does not seem to respect that selection. It seems to always install Eclipse 2023-09 (4.29). I selected 2021-12, but in the installer logs (`<installdir>/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.oomph.setup/setup.log`):
```
[2023-12-01 13:32:12] Product org.eclipse.products.org.eclipse.platform.ide.2021-12
[...]
[2023-12-01 13:32:12] Performing P2 Director (Eclipse Platform (2021-12) + JRE 11.0.21)
[...]
[2023-12-01 13:33:21] Installing org.eclipse.platform [4.29.0.v20230903-1000]
```

And sure enough, the newest version is what gets installed:
![Screen Shot 2023-12-01 at 2 33 01 PM](https://github.com/tlaplus/tlaplus/assets/1393639/b3bedc4a-1a21-4f96-8d2c-050e5f3b931a)

That version of Eclipse seems to be incompatible with the Toolbox project. After install, during Eclipse's project setup, I get this message:
![Screen Shot 2023-12-01 at 2 14 32 PM](https://github.com/tlaplus/tlaplus/assets/1393639/db3ced8f-a73f-40a6-bc1a-e408fdecf06c)

And forevermore the installed IDE seems completely unusable:
![Screen Shot 2023-12-01 at 2 14 43 PM](https://github.com/tlaplus/tlaplus/assets/1393639/c946ec99-e78b-4625-ba85-1e888f7c087c)

Indeed, the IDE logs (`<installdir>/ws/.metadata/.log`) show a verbose and cryptic error. The entire thing is not likely to be useful, but it includes gems like
```
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 32
Exception Details:
  Location:
    org/eclipse/jdt/internal/core/JavaModelManager.createOutputStream(Ljava/io/File;)Ljava/io/OutputStream; @3: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b201 3f99 001d bb0a 7959 bb0a 7b59 bb0a
    0000010: 7d59 2bb7 0a7f 1120 00b7 0a80 b70a 83b0
    0000020: bb0a 7959 bb0a 7d59 2bb7 0a7f b70a 83b0
    0000030:                                        

	at org.eclipse.jdt.core.JavaCore.start(JavaCore.java:6481)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 111 more
```

I did my best to diagnose and fix whatever the installer was doing wrong, but without success.

**Comment by Calvin-L** [comment]
The problem seems similar to the report in #740. It is possible that the `TLA.setup` file needs some adjustment (see @Jack1106012623's [comment in that issue](https://github.com/tlaplus/tlaplus/issues/740#issuecomment-1175947636)).

**Comment by lemmy** [comment]
It looks similar here.  One clue might be that Eclipse/Oomph seems to pick up Java 21 (`OpenJDK Runtime Environment 21.0.1+12-LTS`) => Verify Error, even though I selected Java 17 in the Oomph installer.

**Comment by lemmy** [comment]
Try this TLA.setup:

```diff
diff --git a/general/ide/TLA.setup b/general/ide/TLA.setup
index 1d0ba2f8e..8784d3c7d 100644
--- a/general/ide/TLA.setup
+++ b/general/ide/TLA.setup
@@ -56,33 +56,16 @@
       storageURI="scope://Workspace"/>
   <setupTask
       xsi:type="setup.p2:P2Task">
-    <requirement
-        name="org.eclipse.swtbot.eclipse.feature.group"
-        filter=""/>
-    <requirement
-        name="org.eclipse.swtbot.feature.group"/>
-    <requirement
-        name="org.eclipse.ajdt.feature.group"/>
     <requirement
         name="org.eclipse.pde.feature.group"/>
     <requirement
         name="org.eclipse.egit.feature.group"/>
-    <requirement
-        name="org.eclipse.e4.tools.spies.feature.feature.group"/>
-    <requirement
-        name="org.eclipse.rcptt.platform.feature.group"/>
-    <repository
-        url="http://download.eclipse.org/technology/swtbot/releases/latest/"/>
-    <repository
-        url="http://download.eclipse.org/tools/ajdt/410/dev/update/"/>
     <repository
         url="http://download.eclipse.org/technology/m2e/releases/latest/"/>
     <repository
         url="http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/"/>
     <repository
         url="jar:https://raw.githubusercontent.com/tlaplus/tlaplus/master/toolbox/org.lamport.tla.toolbox.product.product/cachedTargetPlatform/com.abstratt.eclipsegraphviz.repository-2.5.201812.zip!/"/>
-    <repository
-        url="https://download.eclipse.org/rcptt/release/2.5.1/repository/"/>
     <description>Install the tools needed in the IDE to work with the source code for ${scope.project.label}</description>
   </setupTask>
   <setupTask
```

**Comment by Calvin-L** [comment]
Yes, that seems to be enough for the install to succeed. :)

The initial project checkout ends with an angry message:

```
Performing Target Platform TLA+ Toolbox
Fetching content.jar from https://download.eclipse.org/tools/ajdt/410/dev/update/ajdt-e410-2.2.4.202007241909/ (12.18kB)
Fetching p2.index from https://download.eclipse.org/tools/orbit/downloads/drops/R20180905201904/repository/ (134B)
Fetching compositeContent.xml from https://download.eclipse.org/tools/orbit/downloads/drops/R20180905201904/repository/
Fetching content.jar from https://download.eclipse.org/tools/orbit/downloads/drops/R20180829150157/repository/ (109.08kB)
Connecting Git team provider.
Fetching p2.index from https://download.eclipse.org/tools/orbit/downloads/drops2/R20180905201904/repository/ (172B)
Searching for markers
Process resource updates
Fetching content.xml.xz from https://download.eclipse.org/tools/orbit/downloads/drops2/R20180905201904/repository/ (68.54kB)
Fetching p2.index from https://download.eclipse.org/tools/orbit/downloads/drops/R20210602031627/repository/ (134B)
Fetching compositeContent.xml from https://download.eclipse.org/tools/orbit/downloads/drops/R20210602031627/repository/
Fetching content.jar from https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/ (106.52kB)
Fetching p2.index from https://download.eclipse.org/tools/orbit/downloads/drops2/R20210602031627/repository/ (172B)
Fetching content.xml.xz from https://download.eclipse.org/tools/orbit/downloads/drops2/R20210602031627/repository/ (97.94kB)
Fetching p2.index from https://download.eclipse.org/technology/swtbot/releases/2.7.0/ (172B)
Fetching content.xml.xz from https://download.eclipse.org/technology/swtbot/releases/2.7.0/ (11.69kB)
Fetching content.jar from https://lemmster.de/jclouds2p2/ (16.23kB)
Fetching p2.index from https://download.eclipse.org/eclipse/updates/4.18/R-4.18-202012021800/ (142B)
Fetching content.xml.xz from https://download.eclipse.org/eclipse/updates/4.18/R-4.18-202012021800/ (122.44kB)
Fetching p2.index from https://archive.eclipse.org/egit/updates-5.9/ (172B)
Fetching content.xml.xz from https://archive.eclipse.org/egit/updates-5.9/ (20.88kB)
Fetching p2.index from https://lemmster.de/Pdf4Eclipse/ (173B)
Fetching content.xml.xz from https://lemmster.de/Pdf4Eclipse/ (5.81kB)
Fetching p2.index from https://lemmster.de/eclipse-jdk-bundles/ (172B)
Fetching content.xml.xz from https://lemmster.de/eclipse-jdk-bundles/ (2.8kB)
Fetching p2.index from jar:https://raw.githubusercontent.com/tlaplus/tlaplus/master/toolbox/org.lamport.tla.toolbox.product.product/cachedTargetPlatform/com.abstratt.eclipsegraphviz.repository-2.5.201812.zip!/ (172B)
Fetching content.jar from jar:https://raw.githubusercontent.com/tlaplus/tlaplus/master/toolbox/org.lamport.tla.toolbox.product.product/cachedTargetPlatform/com.abstratt.eclipsegraphviz.repository-2.5.201812.zip!/ (4.17kB)
Fetching p2.index from https://download.eclipse.org/releases/2018-09/201809191002/ (142B)
Fetching content.xml.xz from https://download.eclipse.org/releases/2018-09/201809191002/ (864.48kB)
Fetching p2.index from https://download.eclipse.org/mylyn/releases/3.24/ (126B)
Fetching compositeContent.xml from https://download.eclipse.org/mylyn/releases/3.24/
Fetching content.jar from https://download.eclipse.org/mylyn/drops/3.24.3/v20190124-2014/ (54.88kB)
Fetching content.jar from https://download.eclipse.org/mylyn/drops/3.24.2/v20180905-2014/ (54.77kB)
Fetching content.jar from https://download.eclipse.org/mylyn/drops/3.24.1/v20180619-2220/ (64.93kB)
Fetching content.jar from https://download.eclipse.org/mylyn/drops/3.24.0/v20180613-1723/ (61.01kB)
Fetching p2.index from https://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/ (172B)
Fetching content.xml.xz from https://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/ (7.71kB)
Calculating requirements and dependencies.
Searching for markers
Process resource updates
Cannot complete the request.  Generating details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.setup.pde.impl.TargetPlatformTaskImpl.perform(TargetPlatformTaskImpl.java:298)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: Equinox Core SDK 3.21.0.v20201107-1818 (org.eclipse.equinox.core.sdk.feature.group 3.21.0.v20201107-1818)
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement for filter properties ~= $0: Equinox Core SDK 3.21.0.v20201107-1818 (org.eclipse.equinox.core.sdk.feature.group 3.21.0.v20201107-1818) requires 'org.eclipse.equinox.p2.iu; org.eclipse.equinox.security.macosx [1.101.200.v20190903-0934,1.101.200.v20190903-0934]' but it could not be found

Took 87 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

But the IDE is in a usable state, modulo a few dependency-related errors that I might be able to fix up myself:
![Screen Shot 2023-12-04 at 1 13 15 PM](https://github.com/tlaplus/tlaplus/assets/1393639/6e873128-fdd1-433b-8eae-2c4ca39c6a4b)

**Comment by ahelwer** [comment]
I also get an error on macOS when running `mvn install -Dmaven.test.skip=true`:
>[ERROR] Cannot resolve target definition:
>[ERROR]   Software being installed: org.eclipse.contribution.weaving.feature.group 2.2.4.202007241909
>[ERROR]   Missing requirement: org.eclipse.core.jobs 3.10.100.v20180817-1215 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
>[ERROR]   Missing requirement: org.eclipse.core.jobs 3.10.1000.v20200909-1312 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
>[ERROR]   Cannot satisfy dependency: org.eclipse.contribution.weaving.feature.group 2.2.4.202007241909 depends on: org.eclipse.equinox.p2.iu; org.eclipse.core.runtime 0.0.0
>[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.15.0.v20180817-1401 depends on: osgi.bundle; org.eclipse.core.jobs [3.10.0,4.0.0)
>[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.20.0.v20201027-1526 depends on: osgi.bundle; org.eclipse.core.jobs [3.10.0,4.0.0)
>[ERROR]
>[ERROR] Failed to resolve target definition /Users/ahelwer/src/tlaplus/java-tools/toolbox/org.lamport.tla.toolbox.product.product/TLAToolbox.target: See log for details -> [Help 1]
>[ERROR]
>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
>[ERROR]
>[ERROR] For more information about the errors and possible solutions, please read the following articles:
>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by lemmy** [comment]
@ahelwer Does the maven build work with https://github.com/tlaplus/tlaplus/pull/940 ?

**Comment by lemmy** [comment]
Related: https://github.com/tlaplus/tlaplus/commit/2c4b67b7c20c52e34ada410a9f74a40da0e280bf

**Comment by lemmy** [comment]
I will consider this done.
