### ISSUE TITLE
JLine StringIndexOutOfBoundsException in TLA+ REPL

### ISSUE THREAD

**Issue by pera** [tlaplus/tlaplus#861]
## Description

The version of JLine currently used by the REPL (i.e. JLine 3.14.1) throws an exception right at the start in some Linux terminals. Upgrading the library fixes this issue (e.g. the Scala REPL bug report for the same problem: https://github.com/scala/bug/issues/12004).

## Expected Behavior
When running `tla` on rxvt a new REPL session should start.

## Actual Behavior
When running `tla` on rxvt this exception is thrown:
```
Exception in thread "main" java.io.IOError: java.lang.StringIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at org.jline.utils.Curses.tputs(Curses.java:62)
	at org.jline.utils.Curses.tputs(Curses.java:45)
	at org.jline.keymap.KeyMap.key(KeyMap.java:243)
	at org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:6095)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:6103)
	at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5813)
	at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5789)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:293)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
	at tlc2.REPL.main(REPL.java:229)
Caused by: java.lang.StringIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4575)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1535)
	at org.jline.utils.Curses.doTputs(Curses.java:359)
	at org.jline.utils.Curses.tputs(Curses.java:60)
	... 18 more
```

## Steps to Reproduce
1. Run `tla` on a (u)rxvt terminal emulator.

## Steps Taken to Fix
An easy workaround is to start the REPL with the following environment variable `TERM=xterm-256color`

## Possible Fix
Upgrading JLine to 3.16.0 or later should fix this. The [latest version](https://github.com/jline/jline3/releases) is 3.25.0.

## Your Environment
 - TLC version: 2.18
 - Operating System: Arch Linux

**Comment by lemmy** [comment]
@pera @will62794 Could either one of you please provide a PR?

**Comment by lemmy** [comment]
Thanks!

**Comment by pera** [comment]
Thank you ^^

**Comment by lemmy** [comment]
I believe the following warning is new when launching the REPL: `Jan 19, 2024 8:32:25 AM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`.  Also, the REPL's history (up arrow) is now broken on my macOS.

**Comment by pera** [comment]
@lemmy There is an interesting thread about this issue here: https://github.com/ArcadeData/arcadedb/issues/1331
Unfortunately I don't have any Mac OS or Windows machine where I could try it but I will create a PR to add `jline-terminal-jansi` so you can test it at least on your mac

**Comment by lemmy** [comment]
Does the history work on Linux?

**Comment by lemmy** [comment]
> Does the history work on Linux? Can you move the cursor with arrow keys?

REPL does not exhibit broken behavior on Ubuntu 22.04.
