### ISSUE TITLE
Pluscal translator crush (very easy fix)

### ISSUE THREAD

**Issue by jackmalkovick** [tlaplus/tlaplus#874]
## Description
When translating my spec from pluscal to tla I've got this exception:

```
pcal.trans Version 1.11 of 31 December 2020
Labels added.
Parsing completed.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 107 out of bounds for length 107
	at pcal.AST.Indent(AST.java:972)
	at pcal.AST.VectorToSeqString(AST.java:1001)
	at pcal.AST$Assign.toString(AST.java:539)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST.VectorOfVectorsToSeqString(AST.java:1041)
	at pcal.AST$Either.toString(AST.java:642)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST.VectorOfVectorsToSeqString(AST.java:1041)
	at pcal.AST$Either.toString(AST.java:642)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST.VectorOfVectorsToSeqString(AST.java:1041)
	at pcal.AST$Either.toString(AST.java:642)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST.VectorOfVectorsToSeqString(AST.java:1041)
	at pcal.AST$Either.toString(AST.java:642)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST.VectorOfVectorsToSeqString(AST.java:1041)
	at pcal.AST$Either.toString(AST.java:642)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:626)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$If.toString(AST.java:629)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$LabelIf.toString(AST.java:740)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$While.toString(AST.java:524)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$LabeledStmt.toString(AST.java:502)
	at pcal.AST.VectorToSeqString(AST.java:1006)
	at pcal.AST$Uniprocess.toString(AST.java:257)
	at pcal.trans.performTranslation(trans.java:1015)
	at pcal.trans.performTranslation(trans.java:576)
	at pcal.trans.runMe(trans.java:374)
	at pcal.trans.main(trans.java:305)

```
## Expected Behavior
Translation succeeds.

## Actual Behavior
Crushes with the given stack trace.

## Steps to Reproduce
I've run
`java -cp tla2tools.jar pcal.trans mySpec.tla`
In Toolbox fails silently.

## Steps Taken to Fix
Unfortunately I'm not allowed to share the spec that reproduces the bug.

## Possible Fix
The fix is replacing in PlusCal's AST.java the line
`public static int[] curIndent =  {0, 0, ...}`
with something like
`public static int[] curIndent = new int[2048];`

## Your Environment
Both Linux and Windows

**Comment by lemmy** [comment]
Can you provide a PR?

**Comment by jackmalkovick** [comment]
I tried to push a branch in order to make a pull request but 
`remote: Permission to tlaplus/tlaplus.git denied to jackmalkovick`
I'm sure I'm not doing something right

**Comment by ahelwer** [comment]
@jackmalkovick you need to fork this repo to your own account before you can create a branch. You don't have permissions to push to this repo, but you will have permissions to push to your own fork of this repo. Then you can create a PR off of that.

**Comment by lemmy** [comment]
@jackmalkovick Please reopen this if you intend to work on it.
