### ISSUE TITLE
Flaky unit tests

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#943]
## Description
The unit tests sometimes fail in GitHub CI. Two examples:
 - https://github.com/tlaplus/tlaplus/pull/925#issuecomment-2115885840
 - CI failure for a commit that passed PR CI and local tests on my machine: https://github.com/tlaplus/tlaplus/actions/runs/9487536859/attempts/1 --- unfortunately the log does not include the test output :(

I don't know if the examples are related, but they may be pointing at some obscure race condition in TLC or in the test infrastructure.

**Comment by lemmy** [comment]
Can you check if this is limited to Trace* tests?  That's a relatively new set of tests and feature of the test suite.

**Comment by Calvin-L** [comment]
I don't think we have enough data points to say for sure. It's true that both of the failures we've seen so far have been Trace* tests, but that's hardly conclusive.

**Comment by Calvin-L** [comment]
I set up a script to run the tests over and over on my laptop overnight. Here's an example where `tlc2.TraceExpressionSpecSafetySimTest` failed:

```
TLC2 Version 2.18 of Day Month 20??
Running Random Simulation with seed 1 with 1 worker on 8 cores with 7282MB heap and 0MB offheap memory [pid: 6197] (Mac OS X 14.5 aarch64, Azul Systems, Inc. 21.0.2 x86_64).
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/test-model/TESpecTest/TESpecTest.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/Naturals.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/_TLAPlusDebugger.tla
Semantic processing of module Naturals
Semantic processing of module _TLAPlusDebugger
Semantic processing of module TESpecTest
Starting... (2024-06-13 09:30:58)
Failed to match EvaluatingValueTest!A operator override from file:/Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/test-class/tlc2/tool/EvaluatingValueTest.class with signature: <Java Method: public static synchronized tlc2.value.impl.Value tlc2.tool.EvaluatingValueTest.action(tlc2.tool.impl.Tool,tla2sany.semantic.ExprOrOpArgNode[],tlc2.util.Context,tlc2.tool.TLCState,tlc2.tool.TLCState,int,tlc2.tool.coverage.CostModel)> (no such module).
Warning: Failed to match Get operator override from UserModuleOverrideAnnotation with signature: public static tlc2.value.impl.Value tlc2.overrides.UserModuleOverrideAnnotationImpl.getNumberOne() (no such module).
(Use the -nowarning option to disable this warning.)
Warning: Failed to match Get operator override from NoSuchModule with signature: public static tlc2.value.impl.Value tlc2.overrides.UserModuleOverrideAnnotationImpl.noSuchModule() (no such module).
Warning: Failed to match Get2 operator override from UserModuleOverrideAnnotation with signature: public static tlc2.value.impl.Value tlc2.overrides.UserModuleOverrideAnnotationImpl.Get2() (no such module).
Warning: Failed to match Get2 operator override from UserModuleOverrideAnnotation with signature: public static tlc2.value.impl.Value tlc2.overrides.UserModuleOverrideAnnotationImpl.Get2(tlc2.value.impl.Value) (no such module).
Warning: Failed to match NoSuchIdentifier operator override from UserModuleOverrideAnnotation with signature: public static tlc2.value.impl.Value tlc2.overrides.UserModuleOverrideAnnotationImpl.noSuchIdentifier() (no such module).
Computed 1 initial states...
Debugger is listening on 0.0.0.0/0.0.0.0:46502
Error: Invariant Safety is violated.
Error: The behavior up to this point is:
State 1: <Init line 18, col 5 to line 19, col 16 of module TESpecTest>
/\ x = 0
/\ y = FALSE

State 2: <Increment line 22, col 5 to line 23, col 14 of module TESpecTest>
/\ x = 1
/\ y = TRUE

State 3: <Increment line 22, col 5 to line 23, col 14 of module TESpecTest>
/\ x = 2
/\ y = FALSE

State 4: <Increment line 22, col 5 to line 23, col 14 of module TESpecTest>
/\ x = 3
/\ y = TRUE

The number of states generated: 4
Simulation using seed 1 and aril 0
Progress: 4 states checked, 1 traces generated (trace length: mean=0, var(x)=0, sd=0)
Finished in 00s at (2024-06-13 09:30:58)
Trace exploration spec path: states/TESpecTest_TTrace_1718296257.tla
Parsing file /Users/cloncari/src/tlaplus/states/TESpecTest_TTrace_1718296257.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/Sequences.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/TLCExt.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/test-model/TESpecTest/TESpecTest.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/Toolbox.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/Naturals.tla
Parsing file /Users/cloncari/src/tlaplus/tlatools/org.lamport.tlatools/class/tla2sany/StandardModules/TLC.tla
Parsing file /Users/cloncari/src/tlaplus/states/tlc2.TraceExpressionSpecSafetySimTest/13340318255486517271/TESpecTest_TEExpression.tla (/Users/cloncari/src/tlaplus/states/TESpecTest_TTrace_1718296257.tla)

Fatal errors while parsing TLA+ spec in file TESpecTest_TTrace_1718296257

tla2sany.semantic.AbortException
*** Abort messages: 1

Unknown location

Cannot find source file for module TESpecTest_TETrace imported in module TESpecTest_TTrace_1718296257.
```

...as it turns out, the problem is that my laptop ran out of disk space. 😓 But, the error message matches [the one we saw before](https://github.com/tlaplus/tlaplus/pull/925#issuecomment-2115885840).

Is it possible that the CI machines do not have enough disk space to consistently run the tests?

**Comment by lemmy** [comment]
One hypothesis is that the second TLC process runs before its input file (`TESpecTest_TTrace_1718296257`) is ready.

**Comment by Calvin-L** [comment]
Do you have any guess how that could happen?

**Comment by lemmy** [comment]
Unfortunately not.

**Comment by Calvin-L** [comment]
My current guess is that two instances of `TraceExpressionSpecTest` running in parallel might write to the same `TESpecTest_TTrace_XXX.tla` file. The only thing that gives them separate names is the current timestamp in milliseconds, which fills in the `X`s.

**Comment by ahelwer** [comment]
I've been running all the TraceExpressionSpec* tests in parallel now for about an hour after modifying the ant test-set target to do so, but unfortunately haven't run into a failure yet. That said I think your guess is a good one so I will write a fix for that.

**Comment by lemmy** [comment]
<img width="1295" alt="image" src="https://github.com/tlaplus/tlaplus/assets/88777/381b8174-772e-48b4-82e0-9155732265e1">


```java
util.Assert$TLCRuntimeException: Unable not rename file during the clean-up.
	at util.Assert.fail(Assert.java:101)
	at tlc2.tool.fp.DiskFPSet$Flusher.mergeNewEntries(DiskFPSet.java:1114)
	at tlc2.tool.fp.DiskFPSet$Flusher.flushTable(DiskFPSet.java:1064)
	at tlc2.tool.fp.MSBDiskFPSetTest2.testHighFingerprint2(MSBDiskFPSetTest2.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.nio.file.FileSystemException: C:\Users\RUNNER~1\AppData\Local\Temp\tlc2.tool.fp.MSBDiskFPSetTest21718993886316.fp: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:384)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at util.FileUtil.replaceFile(FileUtil.java:219)
	at tlc2.tool.fp.DiskFPSet$Flusher.mergeNewEntries(DiskFPSet.java:1112)
```

**Comment by lemmy** [comment]
One more data point at https://github.com/tlaplus/tlaplus/actions/runs/9618971137/job/26534367237

<img width="868" alt="image" src="https://github.com/tlaplus/tlaplus/assets/88777/efa550b1-9421-4ae7-9374-6e2c6f4340ce">

```java
util.Assert$TLCRuntimeException: Parsing or semantic analysis failed.
	at util.Assert.fail(Assert.java:54)
	at tlc2.tool.impl.SpecProcessor.processSpec(SpecProcessor.java:408)
	at tlc2.tool.impl.SpecProcessor.<init>(SpecProcessor.java:176)
	at tlc2.tool.impl.Spec.<init>(Spec.java:110)
	at tlc2.tool.impl.Tool.<init>(Tool.java:211)
	at tlc2.tool.impl.Tool.<init>(Tool.java:206)
	at tlc2.tool.impl.Tool.<init>(Tool.java:196)
	at tlc2.tool.impl.Tool.<init>(Tool.java:182)
	at tlc2.tool.impl.FastTool.<init>(FastTool.java:50)
	at tlc2.TraceExpressionSpecTest.testSpec(TraceExpressionSpecTest.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at util.IsolatedTestCaseRunner.run(IsolatedTestCaseRunner.java:71)
```

**Comment by Calvin-L** [comment]
There seems to be one related to `MultiFPSetTest` as well: https://github.com/tlaplus/tlaplus/pull/973/checks?check_run_id=26560324569

I've seen this same failure locally a few times (MacOS laptop). I can reproduce it by running `testPutZero()` over and over.

Perhaps this test (and some others) are missing a call to `mpfs.init(...)`? (In the debugger, the `LongArray` does not look properly zero'd, but my understanding of the FPSet implementations is sketchy and this could be a red herring.)

**Comment by Calvin-L** [comment]
I am running it repeatedly in separate VMs (by repeatedly pushing the "run" button in my IDE). So, leftover state from the previous run should not be affecting my findings.

I had some fear that the `testPutZero()` failures were a regression caused by #907, but my surface-level investigation suggests that is not the case.

**Comment by lemmy** [comment]
> Perhaps this test (and some others) are missing a call to `mpfs.init(...)`? (In the debugger, the `LongArray` does not look properly zero'd, but my understanding of the FPSet implementations is sketchy and this could be a red herring.)

If I remember correctly, the general contract is to call `init` after `new`. However, for the memory-based FPSets, `init` is a no-op.  It's possible that `MultiFPSetTest` was created before the `OffHeapDiskFPSet` and was originally used with a memory-based FPSet. I suspect that the heap-based DiskFPSet implementations would also crash if `init` is not called and a disk flush is triggered during a test.

**Comment by Calvin-L** [comment]
I can reliably reproduce the `MultiFPSetTest` failure with this patch:
```diff
diff --git a/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java b/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
index 85e720456..e90023632 100644
--- a/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
+++ b/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
@@ -7,10 +7,12 @@ import java.util.ArrayList;
 import java.util.Collection;
 import java.util.Iterator;
 import java.util.List;
+import java.util.Random;
 import java.util.concurrent.Callable;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Executors;
 import java.util.concurrent.Future;
+import java.util.concurrent.ThreadLocalRandom;
 
 /*
  * On Java 11 (probably starting with 9) sun.misc.Unsafe is implemented on top
@@ -30,6 +32,7 @@ import java.util.concurrent.Future;
  * command-line.  As we do not want to expose JVM parameters to them, we keep
  * sun.misc.Unsafe for now.
  */
+import sun.misc.Unsafe;
 import tlc2.output.EC;
 import util.Assert;
 import util.TLCRuntime;
@@ -75,8 +78,15 @@ public final class LongArray {
                // (see FP64).
                Assert.check(this.unsafe.addressSize() == (Long.SIZE / 8), EC.GENERAL);
                baseAddress = this.unsafe.allocateMemory(positions << logAddressSize);
+               randomize(unsafe, baseAddress, positions, ThreadLocalRandom.current());
        }
-       
+
+       private static void randomize(Unsafe unsafe, long baseAddress, long positions, Random rng) {
+               for (long i = 0; i < positions; ++i) {
+                       unsafe.putAddress(baseAddress + i*8, Math.abs(rng.nextLong()));
+               }
+       }
+
        LongArray(final Collection<Long> from) {
                this(from.size());
                
```

**Comment by Calvin-L** [comment]
I think we've caught the worst offenders. I'm going to keep this issue open a little longer to see if we catch more; if not, I will close it in a few days.
