### ISSUE TITLE
Upload code-coverage-report in PR and CI

### ISSUE THREAD

**Issue by FedericoPonzi** [tlaplus/tlaplus#981]
Followup to #932 , we need to upload the generated code-coverage-report in PR and CI builds.

**Comment by FedericoPonzi** [comment]
We can use: https://github.com/marketplace/actions/jacoco-reporter

**Comment by FedericoPonzi** [comment]
just a quick update:
1. the state of jacoco reporter actions doesn't look very bright, the above extension [failed](https://github.com/tlaplus/tlaplus/actions/runs/9800114266/job/27061509863). It's written in powershell apparently.


2. I tried to use `[madrapps/jacoco-report](https://github.com/Madrapps/jacoco-report)`. This extension will post a message in the pr with code coverage (see for example [here](https://github.com/thsaravana/jacoco-playground/pull/24). There's an option to update the message rather than creating a new one every time so no risk of spamming. It currently does not working in my PR, but I suspect it's because I'm working from a fork of the repo.


3. The test `[tlc2/tool/InliningTest.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/InliningTest.java)` is not playing well with Jacoco and fails with:
```
    [junit] junit.framework.AssertionFailedError
    [junit]     at tlc2.tool.InliningTest.notIn(InliningTest.java:130)

```

I assume the instrumentation inserted by Jacoco gets in the way. I will have to add another junit block without jacoco and use it to run this test. By the way, I've added a `System.out.println("methodNameMatches.size = " + methodNameMatches.size());` [here](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/InliningTest.java#L128) and it always print methodNameMatches.size = 0 when running _without_ Jacoco. Not sure if this is expected or not.

**Comment by FedericoPonzi** [comment]
It is working on my pr to my fork: https://github.com/FedericoPonzi/tlaplus/pull/1#issuecomment-2209602384 it's a bit funny because the comment gets written once from the macos run and another time by the ubuntu run, but at least it works.

**Comment by lemmy** [comment]
> 3\. The test `[tlc2/tool/InliningTest.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/InliningTest.java)` is not playing well with Jacoco and fails with:
> 
> ```
>     [junit] junit.framework.AssertionFailedError
>     [junit]     at tlc2.tool.InliningTest.notIn(InliningTest.java:130)
> ```
> 
> I assume the instrumentation inserted by Jacoco gets in the way. I will have to add another junit block without jacoco and use it to run this test. By the way, I've added a `System.out.println("methodNameMatches.size = " + methodNameMatches.size());` [here](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/InliningTest.java#L128) and it always print methodNameMatches.size = 0 when running _without_ Jacoco. Not sure if this is expected or not.

`InliningTest` makes sure that the methods on the hot path get properly inlined.  It is, thus, sensitive to tools like JaCoCo that post-process the bytecode.  I presume JaCoCo's wrapping of TLC method to collect coverage elevates some method sizes beyond the JDK max inlining threshold.  Perhaps, JaCoCo should not be added to the `test` target?
Here is the reworded and corrected version:

`InliningTest` ensures that methods on the hot path are properly inlined.  Therefore, it is sensitive to tools like JaCoCo that post-process the bytecode.  I suspect JaCoCo's wrapping of TLC methods to collect coverage increases some method sizes beyond the JDK's maximum inlining threshold.  Perhaps JaCoCo should not be included in the `test` target?

**Comment by FedericoPonzi** [comment]
>  Perhaps JaCoCo should not be included in the test target?

The alternative would be to run the test-dist target, would that be acceptable? It will increase the run time of the ci

**Comment by FedericoPonzi** [comment]
Trying to move the discussion from the [PR](https://github.com/tlaplus/tlaplus/pull/982#discussion_r1669265946).
The alternatives are:
1. Run test-dist after test, upload code-coverage and publish comment using github action
2. Run test-dist in a separate job
3. Update test target to include code coverage and put inlining test in a separate junit. 
4. Just skip this work altogether.

Currently the [pr](https://github.com/tlaplus/tlaplus/pull/982) implements the first strategy and seems to be working fine to me. The concern raised by Andrew @ahelwer is that it will increase the build time (it increases build time from 26m to xxm for macos build and from 11m to xxm for the ubuntu build -- I'll update these later). I think we can pick either strategy, and reevaluate in a later point. This is not urgent at all, but I could use some inputs on how to move this forward

**Comment by ahelwer** [comment]
I vote for (3). This is just about pulling out a single unit test for inlining that doesn't play nice with the bytecode changes jacoco makes. We already have two `junit` tasks in the `test` target, one for tests that cannot be run in parallel (since they open network ports on localhost) and another for tests that can. From this we can tell the change will just add around 50 lines of XML to `customBuild.xml`. I do really like the idea of getting code coverage results for our testing, because I know there are gaps but I don't know where (and I like writing tests). It would also be a nice entrypoint for new contributors.

I don't really like a solution that involves running largely the exact same set of tests twice in a row, since I have the usual engineer's dislike of waste and also there is a climate impact to all these CI runs. On that note perhaps we should consider adding [this task](https://github.com/green-coding-solutions/eco-ci-energy-estimation) to the CI, which is incredibly cool - it looks up the specific datacenter the VM is running in to get the carbon intensity of electricity in the region, then tracks power usage during the CI to very accurately estimate climate impact. It even makes a badge we can add to the README!
