### ISSUE TITLE
Checking liveness with Java assertions enabled can cause an assertion violation in LiveWorker

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#990]
```java
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.AssertionError
java.lang.AssertionError
        at tlc2.tool.liveness.LiveWorker.checkSccs(LiveWorker.java:452)
        at tlc2.tool.liveness.LiveWorker.call(LiveWorker.java:1281)
        at tlc2.tool.liveness.LiveWorker.call(LiveWorker.java:42)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

The initial version of LiveWorker.java [from 15 years](https://github.com/tlaplus/tlaplus/blob/a401ad39044e5014cb07a9588611041c1d55596d/tlatools/src/tlc2/tool/liveness/LiveWorker.java#L167) ago did not assert that no node in the behavior graph is undone/not_done during the final liveness check.  In 2015, through reverse engineering, I concluded that all behavior graph nodes should be marked as done.  Consequently, I [added a Java assertion](https://github.com/tlaplus/tlaplus/commit/67a520fe3ba0c449b533bc95e8cdf895556a2213) and confirmed that none of our tests violated the assertion. However, note that by default, TLC does not run with assertions enabled.

For example, checking the two TLA properties `Unforg_Ltl` and `Agreement_Ltl` of the real-world spec [aba_asyn_byz](https://github.com/tlaplus/Examples/blob/master/specifications/aba-asyn-byz/aba_asyn_byz.tla) causes the assertion to be  violated (regardless of the number of workers).

```tla
$ java -ea -XX:+UseParallelGC -cp tla2tools.jar tlc2.TLC -workers 1 -lncheck final -tool -deadlock specificati
ons/aba-asyn-byz/aba_asyn_byz
@!@!@STARTMSG 2262:0 @!@!@
TLC2 Version 2.18 of Day Month 20?? (rev: fe8a2e3)
@!@!@ENDMSG 2262 @!@!@
@!@!@STARTMSG 2187:0 @!@!@
Running breadth-first search Model-Checking with fp 78 and seed -1380278780051172095 with 1 worker on 8 cores with 7131MB heap and 64MB offheap memory [pid: 20834] (Linux 6.5.0-1022-azure amd64, Microsoft 21.0.3 x86_64, MSBDiskFPSet, DiskStateQueue).
@!@!@ENDMSG 2187 @!@!@
@!@!@STARTMSG 2220:0 @!@!@
Starting SANY...
@!@!@ENDMSG 2220 @!@!@
Parsing file /workspaces/Examples/specifications/aba-asyn-byz/aba_asyn_byz.tla
Parsing file /tmp/tlc-9424142497047159386/Naturals.tla (jar:file:/workspaces/Examples/tla2tools.jar!/tla2sany/StandardModules/Naturals.tla)
Semantic processing of module Naturals
Semantic processing of module aba_asyn_byz
@!@!@STARTMSG 2219:0 @!@!@
SANY finished.
@!@!@ENDMSG 2219 @!@!@
@!@!@STARTMSG 2185:0 @!@!@
Starting... (2024-07-17 16:42:59)
@!@!@ENDMSG 2185 @!@!@
@!@!@STARTMSG 2212:0 @!@!@
Implied-temporal checking--satisfiability problem has 1 branches.
@!@!@ENDMSG 2212 @!@!@
@!@!@STARTMSG 2189:0 @!@!@
Computing initial states...
@!@!@ENDMSG 2189 @!@!@
@!@!@STARTMSG 2269:0 @!@!@
Computed 2 initial states...
@!@!@ENDMSG 2269 @!@!@
@!@!@STARTMSG 2269:0 @!@!@
Computed 4 initial states...
@!@!@ENDMSG 2269 @!@!@
@!@!@STARTMSG 2269:0 @!@!@
Computed 8 initial states...
@!@!@ENDMSG 2269 @!@!@
@!@!@STARTMSG 2190:0 @!@!@
Finished computing initial states: 16 distinct states generated at 2024-07-17 16:42:59.
@!@!@ENDMSG 2190 @!@!@
@!@!@STARTMSG 2200:0 @!@!@
Progress(8) at 2024-07-17 16:43:02: 380,766 states generated (380,766 s/min), 43,284 distinct states found (43,284 ds/min), 17,612 states left on queue.
@!@!@ENDMSG 2200 @!@!@
@!@!@STARTMSG 2200:0 @!@!@
Progress(19) at 2024-07-17 16:44:02: 9,319,279 states generated (8,938,513 s/min), 825,248 distinct states found (781,964 ds/min), 189,086 states left on queue.
@!@!@ENDMSG 2200 @!@!@
@!@!@STARTMSG 2200:0 @!@!@
Progress(21) at 2024-07-17 16:45:02: 17,429,432 states generated (8,110,153 s/min), 1,472,762 distinct states found (647,514 ds/min), 290,754 states left on queue.
@!@!@ENDMSG 2200 @!@!@
@!@!@STARTMSG 2200:0 @!@!@
Progress(23) at 2024-07-17 16:45:59: 24,630,803 states generated (7,201,371 s/min), 2,025,625 distinct states found (552,863 ds/min), 363,547 states left on queue.
@!@!@ENDMSG 2200 @!@!@
@!@!@STARTMSG 2200:0 @!@!@
Progress(23) at 2024-07-17 16:45:59: 24,630,803 states generated, 2,025,625 distinct states found, 363,547 states left on queue.
@!@!@ENDMSG 2200 @!@!@
@!@!@STARTMSG 2192:0 @!@!@
Checking temporal properties for the complete state space with 2025625 total distinct states at (2024-07-17 16:45:59)
@!@!@ENDMSG 2192 @!@!@
@!@!@STARTMSG 1000:1 @!@!@
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.AssertionError
java.lang.AssertionError
        at tlc2.tool.liveness.LiveWorker.checkSccs(LiveWorker.java:452)
        at tlc2.tool.liveness.LiveWorker.call(LiveWorker.java:1281)
        at tlc2.tool.liveness.LiveWorker.call(LiveWorker.java:42)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

@!@!@ENDMSG 1000 @!@!@
```

See also https://github.com/tlaplus/Examples/actions/runs/9966962447/job/27539889230

-----

Semi-related:
https://github.com/tlaplus/Examples/issues/148

**Comment by lemmy** [comment]
> For example, checking the two TLA properties `Unforg_Ltl` and `Agreement_Ltl` of the real-world spec [aba_asyn_byz](https://github.com/tlaplus/Examples/blob/master/specifications/aba-asyn-byz/aba_asyn_byz.tla) causes the assertion to be violated (regardless of the number of workers).

This is a red herring. The `-Dtlc2.TLC.stopAfter=180` property causes TLC to stop state-space exploration preemptively after 90 seconds.

**Comment by lemmy** [comment]
The two tests, `Github971d` and `Github971e`, confirm that the bug fix for https://github.com/tlaplus/tlaplus/issues/971 also prevents this assertion violation.  Consequently, I conclude that we should retain the assertion and expect all nodes of the behavior graph to be done during the final liveness check.  Additionally, this indicates that the bug mentioned in https://github.com/tlaplus/tlaplus/issues/971 also caused unsoundness when checking temporal *liveness* properties, i.e., properties involving e.g. the leads-to operator.

**Comment by lemmy** [comment]
Based on the findings above, I propose to elevate the `assert` statement in the code below to a `RuntimeException` thrown by `util.Assert#check`:

https://github.com/tlaplus/tlaplus/blob/5aa8b19cefeb04c4d6dee703e8413595cd9a97a2/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveWorker.java#L445-L452
